<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>ACUCOBOL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(^......[ a-zA-Z0-9\-]...................................................................*$)</string>
			<key>name</key>
			<string>invalid.illegal.cobol</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.cobol</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.acucobol</string>
</dict>
</plist>
