<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jcl</string>
	</array>
	<key>name</key>
	<string>jcl</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^//\*.*$</string>
			<key>name</key>
			<string>comment.line.jcl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.jcl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.jcl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.jcl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//[A-Za-z0-9\$\#@]*)\s*(COMMAND|CNTL|DD|ENCNTL|EXEC|IF|THEN|ELSE|ENDIF|INCLUDE|JCLIB|JOB|OUTPUT|PEND|PROC|SET|XMIT)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>'.*'</string>
			<key>name</key>
			<string>string.quoted.single.jcl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.dd.language.jcl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i:DSN|DISP|DCB|UNIT|VOL|SYSOUT|SPACE|RECFM|LRECL)=</string>
			<key>name</key>
			<string>variable.language.jcl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.exec.language.jcl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i:PGM|PROC|PARM|ADDRSPC|ACCT|TIME|REGION|COND|DSNME|DATAC)=</string>
			<key>name</key>
			<string>variable.language.jcl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.jcl</string>
</dict>
</plist>
