import { IKnownApis } from "./cobolCallTargets";

export class CBL_APIs implements IKnownApis {
    public url = "https,//www.microfocus.com/documentation/visual-cobol/vc70/DevHub/HRCLRHCALL17.html";
    public name = "Micro Focus CBL Library Routines";
    public apis = new Map<string, string>([
        ["CBL_ABORT_RUN_UNIT", "Aborts the current run unit irrespective of thee of existing threads"],
        ["CBL_ALLOC_DYN_MEM", "Dynamically allocates memory, and can associate it with the calling program."],
        ["CBL_ALLOC_MEM", "Dynamically allocates memory, and can associate allocated heap data with a thread and/or the calling program."],
        ["CBL_ALLOC_SHMEM", ",Dynamically allocates shared memory."],
        ["CBL_ALLOC_THREAD_MEM", "Allocates thread-specific heap memory."],
        ["CBL_AND", "Does a logical AND between the bits of two data items."],
        ["CBL_CANCEL", "Cancels a COBOL program."],
        ["CBL_CANCEL_PROC", "Provides control over program cancels."],
        ["CBL_CFGREAD_DYNFH", "The CBL_CFGREAD_DYNFH option determines whether the File Handler should reread its configuration file for configurable custom file handlers"],
        ["CBL_CFGREAD_EXTFH", "Forces the File Handler to reread its configuration file."],
        ["CBL_CHANGE_DIR", "Changes the current directory."],
        ["CBL_CHECK_FILE_EXIST", "Checks whether a file exists and if it does, returns details of when the file was last modified."],
        ["CBL_CLEAR_SCR", "Clears the whole screen to a specified character and attribute."],
        ["CBL_CLOSE_FILE", "Closes a file opened for byte-stream operations."],
        ["CBL_CLOSE_VFILE", "Closes a heap."],
        ["CBL_COPY_FILE", "Copies a file."],
        ["CBL_CREATE_DIR", "Creates a subdirectory. All the directories in the given path, except the last, must already exist."],
        ["CBL_CREATE_FILE", "Creates a new file and leaves it open for byte-stream operations."],
        ["CBL_CTF_COMP_PROPERTY_GET", "Returns a named property value for a component."],
        ["CBL_CTF_COMP_PROPERTY_SET", "Specifies a value for a component's property."],
        ["CBL_CTF_DEST", "Specifies an output destination by associating (or disassociating) an emitter with (or from) a component or the default emitter list."],
        ["CBL_CTF_EMITTER_PROPERTY_GET", "Returns a named property value for an emitter."],
        ["CBL_CTF_EMITTER_PROPERTY_SET", "Sets a named property value for an emitter."],
        ["CBL_CTF_LEVEL", "Specifies the trace level to be used for a specific component, or the default trace level if a component identifier is not specified."],
        ["CBL_CTF_TRACE", "Outputs an event to one or more output destinations."],
        ["CBL_CTF_TRACER_GET", "Returns a tracer handle that can be passed to other tracing routines to identify a component."],
        ["CBL_CTF_TRACER_LEVEL_GET", "Returns a tracer's current threshold trace level."],
        ["CBL_CTF_TRACER_NOTIFY", "Installs or uninstalls a tracer configuration callback function."],
        ["CBL_CULL_RUN_UNITS", "Clears any dead run units."],
        ["CBL_DEBUGBREAK", "Enables a COBOL program to invoke ."],
        ["CBL_DEBUG_START", "Enables a COBOL program to initiate advanced remote debugging or cross-session debugging."],
        ["CBL_DEBUG_STOP", "Enables a COBOL program to stop or suspend animation."],
        ["CBL_DELETE_DIR", "Deletes a directory. The directory is deleted only if it is empty."],
        ["CBL_DELETE_FILE", "Deletes a file."],
        ["CBL_DIR_SCAN_END", "Terminates a search operation."],
        ["CBL_DIR_SCAN_READ", "Searches for the next entry in the file system using a search handle returned by a previous CBL_DIR_SCAN_START."],
        ["CBL_DIR_SCAN_START", "Initializes a search for a file or directory."],
        ["CBL_EQ", "Does a logical EQUIVALENCE between the bits of two data items."],
        ["CBL_ERROR_PROC", "Installs or removes an error procedure to be invoked automatically when a run-time system error occurs."],
        ["CBL_EVENT_CLEAR", "Clears the specified event."],
        ["CBL_EVENT_CLOSE", "Closes the supplied event handle."],
        ["CBL_EVENT_OPEN_INTRA", "Creates an intra-process event."],
        ["CBL_EVENT_POST", "Posts the specified event."],
        ["CBL_EVENT_WAIT", "Waits for the event to be posted."],
        ["CBL_EXEC_RUN_UNIT", "Creates a synchronous or asynchronous run unit."],
        ["CBL_EXIT_PROC", "Installs or removes a closedown procedure to be invoked automatically when the application terminates."],
        ["CBL_FILENAME_CONVERT", "Converts a filename between space-terminated and null-terminated format."],
        ["CBL_FILENAME_MAX_LENGTH", "Returns the maximum size of a filename that the run-time system and the current operating system can handle. This size does not include any terminators (null or space)."],
        ["CBL_FLUSH_FILE", "Ensures all file buffers for a file are written to disk. This includes both run-time system buffers and operating system buffers."],
        ["CBL_FREE_DYN_MEM", "Frees dynamically allocated memory allocated by the CBL_ALLOC_DYN_MEM routine."],
        ["CBL_FREE_MEM", "Frees dynamically allocated memory."],
        ["CBL_FREE_RECORD_LOCK", "Releases a record lock on a file."],
        ["CBL_FREE_SHMEM", "Frees dynamically allocated shared memory"],
        ["CBL_FREE_THREAD_MEM", "Frees dynamically allocated thread-specific heap memory."],
        ["CBL_GET_CSR_POS", "Returns the cursor position."],
        ["CBL_GET_CURRENT_DIR", "Returns the current directory."],
        ["CBL_GET_EXIT_INFO", "Enables an application to determine under what circumstances an exit procedure has been invoked."],
        ["CBL_GET_KBD_STATUS", "Checks whether there is a character waiting to be read from the keyboard."],
        ["CBL_GET_OS_INFO", "Returns information about the operating system environment."],
        ["CBL_GET_PROGRAM_INFO", "Returns information for a named program, or a program in the current call stack."],
        ["CBL_GET_RECORD_LOCK", "Obtains a record lock on a file."],
        ["CBL_GET_SCR_GRAPHICS", "Returns operating system independent codes for graphics characters."],
        ["CBL_GET_SCR_LINE_DRAW", "Returns a table of values defining the character values required by the run-time system screen output routines to correctly display given line drawing characters."],
        ["CBL_GET_SCR_SIZE", "Returns information about the size of the screen."],
        ["CBL_GET_SHMEM_PTR", "Reads a named value."],
        ["CBL_IMP", "Does a logical IMPLIES between the bits of two data items."],
        ["CBL_JOIN_FILENAME", "Forms a filename by joining together its component parts; that is, the pathname, basename and extension."],
        ["CBL_LOCATE_FILE", "This routine has two uses. It can be used to expand an environment variable in a file specification, where the environment variable contains a list of several paths. It can also determine whether an OPEN INPUT ement using a particular file specification finds the file in a library file or as a separate disk file."],
        ["CBL_MEM_STRATEGY", "Changes the memory strategy for an application dynamically."],
        ["CBL_MEM_VALIDATE", "Validates memory allocations, monitored freed memory, and, if the operating system supports it, compacts memory heaps."],
        ["CBL_MONITOR_BROWSE", "Acquires the specified monitor's browse capability for the current thread, blocking until that capability can be acquired."],
        ["CBL_MONITOR_BROWSE_TO_READ", "Converts monitor browse capability already acquired by the current thread to read capability."],
        ["CBL_MONITOR_BROWSE_TO_WRITE", "Converts monitor browse capability already acquired by the current thread to write capability, blocking until this can be achieved."],
        ["CBL_MONITOR_CLOSE", "Closes the supplied monitor handle."],
        ["CBL_MONITOR_OPEN_INTRA", "Creates a monitor synchronization object for thread synchronization within one process."],
        ["CBL_MONITOR_READ", "Acquires the specified monitor's read capability for the current thread/process, blocking until that capability can be acquired."],
        ["CBL_MONITOR_RELEASE", "Releases any lock currently applied to the specified monitor by CBL_MONITOR_WRITE, CBL_MONITOR_READ or CBL_MONITOR_BROWSE."],
        ["CBL_MONITOR_UNBROWSE", "Releases the monitor's browse capability that was acquired by CBL_MONITOR_BROWSE or CBL_MONITOR_WRITE_TO_BROWSE."],
        ["CBL_MONITOR_UNREAD", "Releases the monitor's read capability that was acquired by CBL_MONITOR_READ or CBL_MONITOR_BROWSE_TO_READ."],
        ["CBL_MONITOR_UNWRITE", "Releases the monitor's write capability that was acquired by CBL_MONITOR_WRITE or CBL_MONITOR_BROWSE_TO_WRITE."],
        ["CBL_MONITOR_WRITE", "Acquires the specified monitor's write capability for the current thread, blocking until that capability can be acquired."],
        ["CBL_MONITOR_WRITE_TO_BROWSE", "Converts monitor write capability already acquired by the current thread to browse capability."],
        ["CBL_MUTEX_ACQUIRE", "Acquires a mutex for the specified thread"],
        ["CBL_MUTEX_CLOSE", "Closes the specified mutex."],
        ["CBL_MUTEX_OPEN_INTRA", "Create an intra-process mutex."],
        ["CBL_MUTEX_RELEASE", "Releases the specified mutex."],
        ["CBL_NLS_CLOSE_MSG_FILE", "Closes a National Locale Support (NLS) message file."],
        ["CBL_NLS_COMPARE", "Compares two strings."],
        ["CBL_NLS_INFO", "Gets/sets national language information."],
        ["CBL_NLS_OPEN_MSG_FILE", "Open a National Locale Support (NLS) message file."],
        ["CBL_NLS_READ_MSG", "Reads a message from a National Locale Support (NLS) message file."],
        ["CBL_NOT", "Does a logical NOT on the bits of a data item."],
        ["CBL_OPEN_FILE", "Opens an existing file for byte-stream operations."],
        ["CBL_OPEN_VFILE", "Opens a heap."],
        ["CBL_OR", "Does a logical OR between the bits of two data items."],
        ["CBL_PUT_SHMEM_PTR", "Creates or updates a named value."],
        ["CBL_READ_FILE", "Reads bytes from a file."],
        ["CBL_READ_KBD_CHAR", "Waits until a character is typed and then reads it with no echo."],
        ["CBL_READ_SCR_ATTRS", "Reads a string of attributes from the screen."],
        ["CBL_READ_SCR_CHARS", "Reads a string of characters from the screen."],
        ["CBL_READ_SCR_CHATTRS", "Reads a string of characters and their attributes from the screen."],
        ["CBL_READ_VFILE", "Reads bytes from a heap."],
        ["CBL_RENAME_FILE", "Changes the name of a file."],
        ["CBL_SCR_ALLOCATE_COLOR", "Finds an entry in the colormap for each of one or more given RGB values."],
        ["CBL_SCR_ALLOCATE_VC_COLOR", "Sets one or more specified virtual colormap entries to the RGB values supplied."],
        ["CBL_SCR_CREATE_VC", "Creates a virtual colormap and copies the contents of the system colormap to it."],
        ["CBL_SCR_DESTROY_VC", "Destroys a virtual colormap, causing the run-time system to revert to using the system colormap."],
        ["CBL_SCR_GET_ATTR_INFO", "Returns information about the attribute system for the environment."],
        ["CBL_SCR_GET_ATTRIBUTES", "Gets the character attribute code, and foreground and background colormap indexes for one or more entries in the attribute table."],
        ["CBL_SCR_NAME_TO_RGB", "Converts a single named color into an RGB value."],
        ["CBL_SCR_QUERY_COLORMAP", "Returns the RGB value for one or more colormap entries."],
        ["CBL_SCR_RESTORE", "Restores an area of the character-mode screen previously saved with a call to the CBL_SCR_SAVE call-by-name routine."],
        ["CBL_SCR_RESTORE_ATTRIBUTES", "Restores the attribute table to the saved values that are associated with the specified buffer handle."],
        ["CBL_SCR_SAVE", "Saves away an area of the screen (text and attributes) for subsequent restoration."],
        ["CBL_SCR_SAVE_ATTRIBUTES", "Saves the current settings of the attribute table."],
        ["CBL_SCR_SET_ATTRIBUTES", "Defines the character attribute, and foreground and background colormap indexes associated with each of one or more COBOL attribute values (attribute table indexes)."],
        ["CBL_SCR_SET_PC_ATTRIBUTES", "Sets up the current COBOL attribute table so as to emulate, as closely as possible, the IBM-PC attribute table."],
        ["CBL_SEMAPHORE_ACQUIRE", "Acquires one of the resources represented by the semaphore by decrementing the associated count."],
        ["CBL_SEMAPHORE_CLOSE", "Closes the specified semaphore."],
        ["CBL_SEMAPHORE_OPEN_INTRA", "Creates an intra-process semaphore."],
        ["CBL_SEMAPHORE_RELEASE", "Releases one of the resources represented by the semaphore by incrementing the associated count."],
        ["CBL_SET_CSR_POS", "Moves the cursor."],
        ["CBL_SPLIT_FILENAME", "Splits a filename into its component parts; that is, the pathname, basename and extension."],
        ["CBL_SUBSYSTEM", "Declares or deallocates subsystems."],
        ["CBL_SWAP_SCR_CHATTRS", "Swaps a string of characters and their attributes with a string from the screen."],
        ["CBL_TEST_RECORD_LOCK", "Tests for an existing record lock on a file."],
        ["CBL_THREAD_CREATE", "Creates a thread from a named entry point."],
        ["CBL_THREAD_CREATE_P", "Creates a thread from a procedure pointer."],
        ["CBL_THREAD_DETACH", "Frees thread resources when the thread terminates."],
        ["CBL_THREAD_EXIT", "Terminates the current thread."],
        ["CBL_THREAD_IDDATA_ALLOC", "Allocates an id-data area for the current thread."],
        ["CBL_THREAD_IDDATA_GET", "Returns a pointer to the id-data area for the specified thread."],
        ["CBL_THREAD_KILL", "Kills the specified thread, terminating it abnormally and detaching all resources associated with it."],
        ["CBL_THREAD_LIST_END", "Used in conjunction with CBL_THREAD_LIST_START and CBL_THREAD_LIST_NEXT to obtain a list of all currently existing threads that the run-time system knows about. It is required to terminate a CBL_THREAD_LIST_START."],
        ["CBL_THREAD_LIST_NEXT", "Used in conjunction with CBL_THREAD_LIST_START and CBL_THREAD_LIST_END to obtain a list of all currently existing threads that the run-time system knows about. The CBL_THREAD_LIST_NEXT call takes returns the next item in the list of threads."],
        ["CBL_THREAD_LIST_START", "Used in conjunction with CBL_THREAD_LIST_NEXT and CBL_THREAD_LIST_END to obtain a list of all currently existing threads that the run-time system knows about."],
        ["CBL_THREAD_LOCK", "Locks most functions of the thread-handling routines."],
        ["CBL_THREAD_PROG_LOCK", "With CBL_THREAD_PROG_UNLOCK, provides a single pre-initialized synchronization object per calling COBOL program"],
        ["CBL_THREAD_PROG_UNLOCK", "With CBL_THREAD_PROG_LOCK, provides a single pre-initialized synchronization object per calling COBOL program"],
        ["CBL_THREAD_RESUME", "Resumes a thread that was or will be suspended by CBL_THREAD_SUSPEND."],
        ["CBL_THREAD_SELF", "Stores the thread identifier of the current thread."],
        ["CBL_THREAD_SLEEP", "Causes the calling thread to give up control to the processor for the given number of milliseconds."],
        ["CBL_THREAD_SUSPEND", "Suspends the current thread."],
        ["CBL_THREAD_UNLOCK", "Unlocks most functions of the thread handling routines."],
        ["CBL_THREAD_WAIT", "Waits for completion of the specified non-detached thread, or returns immediately if the thread has already completed."],
        ["CBL_THREAD_YIELD", "Yields the rest of the current thread's timeslice."],
        ["CBL_TOLOWER", "Converts a string of letters to lower case."],
        ["CBL_TOUPPER", "Converts a string of letters to upper case."],
        ["CBL_TSTORE_CLOSE", "Closes a handle returned by CBL_TSTORE_CREATE."],
        ["CBL_TSTORE_CREATE", "Creates a handle for and specifies the size of a thread-storage area. These values can be used in subsequent calls to CBL_TSTORE_GET. The new thread-storage area is initialized to zeroes."],
        ["CBL_TSTORE_GET", "Gets a pointer to the thread-specific memory specified by CBL_TSTORE_CREATE."],
        ["CBL_WRITE_FILE", "Writes bytes to a file."],
        ["CBL_WRITE_SCR_ATTRS", "Writes a string of attributes to the screen."],
        ["CBL_WRITE_SCR_CHARS", "Writes a string of characters to the screen."],
        ["CBL_WRITE_SCR_CHARS_ATTR", "Writes a string of characters to the screen, giving them all the same attribute."],
        ["CBL_WRITE_SCR_CHATTRS", "Writes a string of characters and their attributes to the screen."],
        ["CBL_WRITE_SCR_N_ATTR", "Writes a specified attribute to a string of positions on the screen."],
        ["CBL_WRITE_SCR_N_CHAR", "Writes a specified character to a string of positions on the screen."],
        ["CBL_WRITE_SCR_N_CHATTR", "Writes a specified character and attribute to a string of positions on the screen."],
        ["CBL_WRITE_SCR_TTY", "Writes a string of characters to the screen starting at the current position and scrolling."],
        ["CBL_WRITE_VFILE", "Writes bytes to a heap."],
        ["CBL_XOR", "Does a logical XOR between the bits of two data items."],
        ["CBL_YIELD_RUN_UNIT", "Yields the remainder of a run-unit's time-slice."],
        ["CBL_GET_FILE_INFO", ""],
        ["CBL_RUNTIME_ERROR", "Forces the application to terminate with a run-time error condition."],
        ["SYSTEM", "The SYSTEM library routine provides a method of executing an operating system command."],
        ["CBL_GET_MOUSE_MASK", "Returns the mouse event mask."],
        ["CBL_GET_MOUSE_POSITION", "Returns the screen position of the mouse pointer."],
        ["CBL_GET_MOUSE_STATUS", "Finds out the number of events in the queue."],
        ["CBL_HIDE_MOUSE", "Makes the mouse pointer invisible."],
        ["CBL_INIT_MOUSE", "Initializes mouse support. This routine must be called before other mouse routines can be called."],
        ["CBL_READ_MOUSE_EVENT", "Reads the mouse event queue and returns information about an event."],
        ["CBL_SET_MOUSE_MASK", "Sets the mouse event mask."],
        ["CBL_SET_MOUSE_POSITION", "Set mouse screen coordinates"],
        ["CBL_SHOW_MOUSE", "Makes the mouse pointer visible."],
        ["CBL_TERM_MOUSE", "Terminates mouse support, releasing internal resources."],
        ["PC_GET_MOUSE_SHAPE", "Get mouse pointer shape"],
        ["PC_SET_MOUSE_HIDE_AREA", "Set mouse hide area"],
        ["PC_SET_MOUSE_SHAPE", "Set mouse pointer shape"],
        ["PC_FIND_DRIVES", "Find valid drives"],
        ["PC_READ_DRIVE", "Read the current drive"],
        ["PC_SET_DRIVE", "Set the current drive"],
        ["PC_WIN_ABOUT", "Add an about box"],
        ["PC_WIN_CHAR_TO_OEM", "Translates a buffer of ANSI characters into the OEM character set."],
        ["PC_WIN_HANDLE", "Obtain the handle of the window"],
        ["PC_WIN_INIT", "Get the Windows startup values"],
        ["PC_WIN_OEM_TO_CHAR", "Translates a buffer of OEM characters into the ANSI character set."],
        ["PC_WIN_YIELD", "Yield control to Windows"],
        ["CBL_FFND_REPORT", "Enables a COBOL program to invoke FaultFinder"],
        ["CBL_MONITOR_BROWSE_TO_WRITE", "Converts monitor browse capability already acquired by the current thread to write capability, blocking until this can be achieved."],
        ["CBL_MONITOR_WRITE_TO_BROWSE", "Converts monitor write capability already acquired by the current thread to browse capability."],
        ["CBL_SEMAPHORE_CLEAR", ""],
        ["CBL_SEMAPHORE_POST", ""],
        ["CBL_SEMAPHORE_WAIT", ""],
        ["CBL_SRV_SERVICE_FLAGS_GET", "Enables a program running within a COBOL container as part of a service to determine the service's execution characteristics."],
        ["CBL_SRV_SERVICE_FLAGS_SET", "Enables a program running within a COBOL container as part of a service to set one or more the service's execution characteristics."]

    ]);

    public examples = new Map<string, string>([
        ["CBL_ALLOC_DYN_MEM", "call \"CBL_ALLOC_DYN_MEM\" using\r\n by reference MEM-POINTER\r\n by value MEM-SIZE\r\n by value MEM-FLAGS\r\n returning MEM-RTNCODE\r\nend-call"],
        ["CBL_ALLOC_MEM", "call \"CBL_ALLOC_MEM\" using\r\n by reference MEM-POINTER\r\n by value MEM-SIZE\r\n by value MEM-FLAGS\r\n returning MEM-RTNCODE\r\nend-call"],
        ["CBL_ALLOC_SHMEM", "call \"CBL_ALLOC_SHMEM\" using\r\n by reference MEM-POINTER\r\n by value MEM-SIZE\r\n by value MEM-FLAGS\r\n returning MEM-RTNCODE\r\nend-call"],
        ["CBL_ALLOC_THREAD_MEM", "call \"CBL_ALLOC_THREAD_MEM\" using\r\n by reference MEM-POINTER\r\n by value MEM-SIZE\r\n by value MEM-FLAGS\r\n returning MEM-RTNCODE\r\nend-call"],
        ["CBL_FREE_DYN_MEM", "call \"CBL_FREE_DYN_MEM\" using\r\n by value MEM-POINTER\r\n returning MEM-RTNCODE\r\nend-call"],
        ["CBL_FREE_MEM", "call \"CBL_FREE_MEM\" using\r\n by value MEM-POINTER\r\n returning MEM-RTNCODE\r\nend-call"],
        ["CBL_FREE_SHMEM", "call \"CBL_FREE_SHMEM\" using\r\n by value MEM-POINTER\r\n returning MEM-RTNCODE\r\nend-call"],
        ["CBL_FREE_THREAD_MEM", "call \"CBL_FREE_THREAD_MEM\" using\r\n by value MEM-POINTER\r\n returning MEM-RTNCODE\r\nend-call"],
        ["CBL_GET_SHMEM_PTR", "call \"CBL_GET_SHMEM_PTR\" using\r\n by reference MEM-NODE-VALUE\r\n by reference ANY\r\n returning MEM-RTNCODE\r\nend-call"],
        ["CBL_PUT_SHMEM_PTR", "call \"CBL_PUT_SHMEM_PTR\" using\r\n by value MEM-NODE-VALUE\r\n by reference ANY\r\n returning MEM-RTNCODE\r\nend-call"],
        ["CBL_MEM_STRATEGY", "call \"CBL_MEM_STRATEGY\" using\r\n by value MEM-FUNC\r\n by reference MEM-STRATEGY-FLAGS\r\n returning MEM-RTNCODE\r\nend-call"],
        ["CBL_MEM_VALIDATE", "call \"CBL_MEM_VALIDATE\" using\r\n by value MEM-FLAGS\r\n by reference MEM-VALIDATE-PARAM\r\n returning MEM-RTNCODE\r\nend-call"],
        ["CBL_AND", "call \"CBL_AND\" using\r\n by reference ANY\r\n by reference ANY\r\n by value LEN\r\n returning RET\r\nend-call"],
        ["CBL_EQ", "call \"CBL_EQ\" using\r\n by reference ANY\r\n by reference ANY\r\n by value LEN\r\n returning RET\r\nend-call"],
        ["CBL_GET_OS_INFO", "call \"CBL_GET_OS_INFO\" using\r\n by reference OS-INFO-BLOCK\r\n returning RET\r\nend-call"],
        ["CBL_IMP", "call \"CBL_IMP\" using\r\n by reference ANY\r\n by reference ANY\r\n by value LEN\r\n returning RET\r\nend-call"],
        ["CBL_NOT", "call \"CBL_NOT\" using\r\n by reference ANY\r\n by value LEN\r\n returning RET\r\nend-call"],
        ["CBL_OR", "call \"CBL_OR\" using\r\n by reference ANY\r\n by reference ANY\r\n by value LEN\r\n returning RET\r\nend-call"],
        ["CBL_TOLOWER", "call \"CBL_TOLOWER\" using\r\n by reference ANY\r\n by value LEN\r\n returning RET\r\nend-call"],
        ["CBL_TOUPPER", "call \"CBL_TOUPPER\" using\r\n by reference ANY\r\n by value LEN\r\n returning RET\r\nend-call"],
        ["CBL_XOR", "call \"CBL_XOR\" using\r\n by reference ANY\r\n by reference ANY\r\n by value LEN\r\n returning RET\r\nend-call"],
        ["CBL_CHANGE_DIR", "call \"CBL_CHANGE_DIR\" using\r\n by reference cblt-alphanum-const\r\n returning CD-RET\r\nend-call"],
        ["CBL_CHECK_FILE_EXIST", "call \"CBL_CHECK_FILE_EXIST\" using\r\n by reference ANY\r\n by reference FE-DETAILS\r\n returning FE-RET\r\nend-call"],
        ["CBL_COPY_FILE", "call \"CBL_COPY_FILE\" using\r\n by reference cblt-alphanum-const\r\n by reference cblt-alphanum-const\r\n returning CF-RET\r\nend-call"],
        ["CBL_CREATE_DIR", "call \"CBL_CREATE_DIR\" using\r\n by reference cblt-alphanum-const\r\n returning CD-RET\r\nend-call"],
        ["CBL_DELETE_DIR", "call \"CBL_DELETE_DIR\" using\r\n by reference cblt-alphanum-const\r\n returning DD-RET\r\nend-call"],
        ["CBL_DELETE_FILE", "call \"CBL_DELETE_FILE\" using\r\n by reference cblt-alphanum-const\r\n returning DF-RET\r\nend-call"],
        ["CBL_DIR_SCAN_END", "call \"CBL_DIR_SCAN_END\" using\r\n by reference DS-HANDLE\r\n returning DS-RET\r\nend-call"],
        ["CBL_DIR_SCAN_READ", "call \"CBL_DIR_SCAN_READ\" using\r\n by reference DS-HANDLE\r\n by reference ANY\r\n returning DS-RET\r\nend-call"],
        ["CBL_DIR_SCAN_START", "call \"CBL_DIR_SCAN_START\" using\r\n by reference DS-HANDLE\r\n by reference ANY\r\n by value DS-ATTRS\r\n by value DS-FLAGS\r\n returning DS-RET\r\nend-call"],
        ["CBL_FILENAME_CONVERT", "call \"CBL_FILENAME_CONVERT\" using\r\n by reference FNC-FUNC\r\n by reference cblt-alphanum-const\r\n by reference ANY\r\n by value FNC-IN-LENGTH\r\n by value FNC-OUT-LENGTH\r\n returning FNC-RET\r\nend-call"],
        ["CBL_FILENAME_MAX_LENGTH", "call \"CBL_FILENAME_MAX_LENGTH\" using\r\n returning FML-RET\r\nend-call"],
        ["CBL_GET_CURRENT_DIR", "call \"CBL_GET_CURRENT_DIR\" using\r\n by value GCD-FLAGS\r\n by value GCD-NAME-LENGTH\r\n by reference ANY\r\n returning GCD-RET\r\nend-call"],
        ["CBL_GET_FILE_INFO", "call \"CBL_GET_FILE_INFO\" using\r\n by value FI-FLAGS\r\n by reference cblt-alphanum-const\r\n by reference FI-DETAILS\r\n returning FI-RET\r\nend-call"],
        ["CBL_JOIN_FILENAME", "call \"CBL_JOIN_FILENAME\" using\r\n by reference SJ-PACKET\r\n by reference ANY\r\n by reference cblt-alphanum-const\r\n by reference cblt-alphanum-const\r\n by reference cblt-alphanum-const\r\n returning SJ-RET\r\nend-call"],
        ["CBL_LOCATE_FILE", "call \"CBL_LOCATE_FILE\" using\r\n by reference cblt-alphanum-const\r\n by reference LF-FUNC\r\n by reference ANY\r\n by reference LF-EXIST-FLAG\r\n by reference LF-PATH-FLAG\r\n returning LF-RET\r\nend-call"],
        ["CBL_RENAME_FILE", "call \"CBL_RENAME_FILE\" using\r\n by reference cblt-alphanum-const\r\n by reference cblt-alphanum-const\r\n returning RF-RET\r\nend-call"],
        ["CBL_SPLIT_FILENAME", "call \"CBL_SPLIT_FILENAME\" using\r\n by reference SJ-PACKET\r\n by reference ANY\r\n returning SJ-RET\r\nend-call"],
        ["CBL_NLS_CLOSE_MSG_FILE", "call \"CBL_NLS_CLOSE_MSG_FILE\" using\r\n by reference MSG-HANDLE\r\n returning RTNCODE\r\nend-call"],
        ["CBL_NLS_COMPARE", "call \"CBL_NLS_COMPARE\" using\r\n by reference cblt-alphanum-const\r\n by reference cblt-alphanum-const\r\n by value STRING-LENGTH\r\n by value STRING-LENGTH\r\n by reference COMPARE-RESULT\r\n returning RTNCODE\r\nend-call"],
        ["CBL_NLS_INFO", "call \"CBL_NLS_INFO\" using\r\n by reference INFO-FUNCTION-CODE\r\n by reference INFO-CATEGORY\r\n by reference ANY\r\n returning RTNCODE\r\nend-call"],
        ["CBL_NLS_OPEN_MSG_FILE", "call \"CBL_NLS_OPEN_MSG_FILE\" using\r\n by reference cblt-alphanum-const\r\n by reference MSG-FILE-NAME-LENGTH\r\n by reference MSG-HANDLE\r\n returning RTNCODE\r\nend-call"],
        ["CBL_NLS_READ_MSG", "call \"CBL_NLS_READ_MSG\" using\r\n by reference MSG-HANDLE-READONLY\r\n by reference MSG-NUMBER-PAIR\r\n by reference ANY\r\n by reference ANY\r\n returning RTNCODE\r\nend-call"],
        ["CBL_ABORT_RUN_UNIT", "call \"CBL_ABORT_RUN_UNIT\" using\r\n by value RTNCODE\r\n returning RTNCODE\r\nend-call"],
        ["CBL_CULL_RUN_UNITS", "call \"CBL_CULL_RUN_UNITS\" using\r\n returning RTNCODE\r\nend-call"],
        ["CBL_ERROR_PROC", "call \"CBL_ERROR_PROC\" using\r\n by reference INSTALL-FLAG\r\n by reference INSTALL-ADDRS\r\n returning RTNCODE\r\nend-call"],
        ["CBL_EXEC_RUN_UNIT", "call \"CBL_EXEC_RUN_UNIT\" using\r\n by reference ANY\r\n by value COMMAND-LINE-LEN\r\n by reference RU-HANDLE\r\n by value STACK-SIZE\r\n by value FLAGS\r\n returning RTNCODE\r\nend-call"],
        ["CBL_EXIT_PROC", "call \"CBL_EXIT_PROC\" using\r\n by reference INSTALL-FLAG\r\n by reference INSTALL-PARAMS\r\n returning RTNCODE\r\nend-call"],
        ["CBL_GET_EXIT_INFO", "call \"CBL_GET_EXIT_INFO\" using\r\n by reference GEI-PARAMS\r\n returning RTNCODE\r\nend-call"],
        ["CBL_SUBSYSTEM", "call \"CBL_SUBSYSTEM\" using\r\n by reference FUNCTION-CODE\r\n by reference ANY\r\n returning RTNCODE\r\nend-call"],
        ["CBL_YIELD_RUN_UNIT", "call \"CBL_YIELD_RUN_UNIT\" using\r\n returning RTNCODE\r\nend-call"],
        ["CBL_RUNTIME_ERROR", "call \"CBL_RUNTIME_ERROR\" using\r\n by value FLAGS\r\n by reference cblt-alphanum-const\r\n returning RTNCODE\r\nend-call"],
        ["SYSTEM", "call \"SYSTEM\" using\r\n by reference ANY\r\n returning C-RTNCODE\r\nend-call"],
        ["CBL_CLOSE_FILE", "call \"CBL_CLOSE_FILE\" using\r\n by reference FILE-HANDLE\r\n returning RETURN-STAT\r\nend-call"],
        ["CBL_CREATE_FILE", "call \"CBL_CREATE_FILE\" using\r\n by reference cblt-alphanum-const\r\n by reference ACCESS-MODE\r\n by reference DENY-MODE\r\n by reference DEVICE\r\n by reference FILE-HANDLE\r\n returning RETURN-STAT\r\nend-call"],
        ["CBL_FLUSH_FILE", "call \"CBL_FLUSH_FILE\" using\r\n by reference FILE-HANDLE\r\n returning RETURN-STAT\r\nend-call"],
        ["CBL_FREE_RECORD_LOCK", "call \"CBL_FREE_RECORD_LOCK\" using\r\n by reference FILE-HANDLE\r\n by reference RECORD-OFFSET\r\n by reference RECORD-LENGTH\r\n by reference RESERVED\r\n returning RETURN-STAT\r\nend-call"],
        ["CBL_GET_RECORD_LOCK", "call \"CBL_GET_RECORD_LOCK\" using\r\n by reference FILE-HANDLE\r\n by reference RECORD-OFFSET\r\n by reference RECORD-LENGTH\r\n by reference RESERVED\r\n returning RETURN-STAT\r\nend-call"],
        ["CBL_OPEN_FILE", "call \"CBL_OPEN_FILE\" using\r\n by reference cblt-alphanum-const\r\n by reference ACCESS-MODE\r\n by reference DENY-MODE\r\n by reference DEVICE\r\n by reference FILE-HANDLE\r\n returning RETURN-STAT\r\nend-call"],
        ["CBL_READ_FILE", "call \"CBL_READ_FILE\" using\r\n by reference FILE-HANDLE\r\n by reference FILE-OFFSET\r\n by reference BYTE-COUNT\r\n by reference FILE-FLAGS\r\n by reference ANY\r\n returning RETURN-STAT\r\nend-call"],
        ["CBL_TEST_RECORD_LOCK", "call \"CBL_TEST_RECORD_LOCK\" using\r\n by reference FILE-HANDLE\r\n by reference RECORD-OFFSET\r\n by reference RECORD-LENGTH\r\n by reference RESERVED\r\n returning RETURN-STAT\r\nend-call"],
        ["CBL_WRITE_FILE", "call \"CBL_WRITE_FILE\" using\r\n by reference FILE-HANDLE\r\n by reference FILE-OFFSET\r\n by reference BYTE-COUNT\r\n by reference FILE-FLAGS\r\n by reference ANY\r\n returning RETURN-STAT\r\nend-call"],
        ["CBL_CLOSE_VFILE", "call \"CBL_CLOSE_VFILE\" using\r\n by value HEAP-ID\r\n returning RTNCODE\r\nend-call"],
        ["CBL_OPEN_VFILE", "call \"CBL_OPEN_VFILE\" using\r\n by reference HEAP-ID\r\n by reference STATUS-WORD\r\n returning RTNCODE\r\nend-call"],
        ["CBL_READ_VFILE", "call \"CBL_READ_VFILE\" using\r\n by value HEAP-ID\r\n by value HEAP-REF\r\n by value HEAP-LENGTH\r\n by reference ANY\r\n returning RTNCODE\r\nend-call"],
        ["CBL_WRITE_VFILE", "call \"CBL_WRITE_VFILE\" using\r\n by value HEAP-ID\r\n by value HEAP-REF\r\n by value HEAP-LENGTH\r\n by reference cblt-alphanum-const\r\n returning RTNCODE\r\nend-call"],
        ["CBL_CLEAR_SCR", "call \"CBL_CLEAR_SCR\" using\r\n by reference ACHARACTER\r\n by reference SCR-ATTRIBUTE\r\n returning RTNCODE\r\nend-call"],
        ["CBL_GET_CSR_POS", "call \"CBL_GET_CSR_POS\" using\r\n by reference SCREEN-POSITION\r\n returning RTNCODE\r\nend-call"],
        ["CBL_GET_KBD_STATUS", "call \"CBL_GET_KBD_STATUS\" using\r\n by reference KEY-STATUS\r\n returning RTNCODE\r\nend-call"],
        ["CBL_GET_SCR_GRAPHICS", "call \"CBL_GET_SCR_GRAPHICS\" using\r\n by reference GRAPHICS-BUFFER\r\n returning RTNCODE\r\nend-call"],
        ["CBL_GET_SCR_LINE_DRAW", "call \"CBL_GET_SCR_LINE_DRAW\" using\r\n by reference LINE-DRAW-FUNCTION-CODE\r\n by reference ANY\r\n returning RTNCODE\r\nend-call"],
        ["CBL_GET_SCR_SIZE", "call \"CBL_GET_SCR_SIZE\" using\r\n by reference SCREEN-DEPTH\r\n by reference SCREEN-WIDTH\r\n returning RTNCODE\r\nend-call"],
        ["CBL_READ_KBD_CHAR", "call \"CBL_READ_KBD_CHAR\" using\r\n by reference CHAR\r\n returning RTNCODE\r\nend-call"],
        ["CBL_READ_SCR_ATTRS", "call \"CBL_READ_SCR_ATTRS\" using\r\n by reference SCREEN-POSITION-CONSTANT\r\n by reference ANY\r\n by reference STRING-LENGTH\r\n returning RTNCODE\r\nend-call"],
        ["CBL_READ_SCR_CHARS", "call \"CBL_READ_SCR_CHARS\" using\r\n by reference SCREEN-POSITION-CONSTANT\r\n by reference ANY\r\n by reference STRING-LENGTH\r\n returning RTNCODE\r\nend-call"],
        ["CBL_READ_SCR_CHATTRS", "call \"CBL_READ_SCR_CHATTRS\" using\r\n by reference SCREEN-POSITION-CONSTANT\r\n by reference ANY\r\n by reference ANY\r\n by reference STRING-LENGTH\r\n returning RTNCODE\r\nend-call"],
        ["CBL_SCR_ALLOCATE_COLOR", "call \"CBL_SCR_ALLOCATE_COLOR\" using\r\n by reference TABLE-COUNT\r\n by reference ANY\r\n by reference ANY\r\n by reference ANY\r\n returning RTNCODE\r\nend-call"],
        ["CBL_SCR_ALLOCATE_VC_COLOR", "call \"CBL_SCR_ALLOCATE_VC_COLOR\" using\r\n by reference TABLE-COUNT\r\n by reference ANY\r\n by reference ANY\r\n returning RTNCODE\r\nend-call"],
        ["CBL_SCR_CREATE_VC", "call \"CBL_SCR_CREATE_VC\" using\r\n returning RTNCODE\r\nend-call"],
        ["CBL_SCR_DESTROY_VC", "call \"CBL_SCR_DESTROY_VC\" using\r\n returning RTNCODE\r\nend-call"],
        ["CBL_SCR_GET_ATTRIBUTES", "call \"CBL_SCR_GET_ATTRIBUTES\" using\r\n by reference TABLE-COUNT\r\n by reference ANY\r\n by reference ANY\r\n returning RTNCODE\r\nend-call"],
        ["CBL_SCR_GET_ATTR_INFO", "call \"CBL_SCR_GET_ATTR_INFO\" using\r\n by reference SCR-ATTRIBUTE-INFORMATION\r\n returning RTNCODE\r\nend-call"],
        ["CBL_SCR_NAME_TO_RGB", "call \"CBL_SCR_NAME_TO_RGB\" using\r\n by reference cblt-alphanum-const\r\n by reference ANY\r\n returning RTNCODE\r\nend-call"],
        ["CBL_SCR_QUERY_COLORMAP", "call \"CBL_SCR_QUERY_COLORMAP\" using\r\n by reference TABLE-COUNT\r\n by reference cblt-x4-compx-const\r\n by reference ANY\r\n returning RTNCODE\r\nend-call"],
        ["CBL_SCR_RESTORE", "call \"CBL_SCR_RESTORE\" using\r\n by value SCR-FLAGS\r\n by value SCR-HANDLE\r\n returning NEW-RTNCODE\r\nend-call"],
        ["CBL_SCR_RESTORE_ATTRIBUTES", "call \"CBL_SCR_RESTORE_ATTRIBUTES\" using\r\n by reference SCR-HANDLE\r\n returning RTNCODE\r\nend-call"],
        ["CBL_SCR_SAVE", "call \"CBL_SCR_SAVE\" using\r\n by value SCR-FLAGS\r\n by value TOP-LINE\r\n by value BOTTOM-LINE\r\n returning SCR-HANDLE\r\nend-call"],
        ["CBL_SCR_SAVE_ATTRIBUTES", "call \"CBL_SCR_SAVE_ATTRIBUTES\" using\r\n by reference SCR-HANDLE\r\n returning RTNCODE\r\nend-call"],
        ["CBL_SCR_SET_ATTRIBUTES", "call \"CBL_SCR_SET_ATTRIBUTES\" using\r\n by reference TABLE-COUNT\r\n by reference cblt-x1-compx\r\n by reference ANY\r\n returning RTNCODE\r\nend-call"],
        ["CBL_SCR_SET_PC_ATTRIBUTES", "call \"CBL_SCR_SET_PC_ATTRIBUTES\" using\r\n returning RTNCODE\r\nend-call"],
        ["CBL_SET_CSR_POS", "call \"CBL_SET_CSR_POS\" using\r\n by reference SCREEN-POSITION-CONSTANT\r\n returning RTNCODE\r\nend-call"],
        ["CBL_SWAP_SCR_CHATTRS", "call \"CBL_SWAP_SCR_CHATTRS\" using\r\n by reference SCREEN-POSITION-CONSTANT\r\n by reference ANY\r\n by reference ANY\r\n by reference STRING-LENGTH\r\n returning RTNCODE\r\nend-call"],
        ["CBL_WRITE_SCR_ATTRS", "call \"CBL_WRITE_SCR_ATTRS\" using\r\n by reference SCREEN-POSITION-CONSTANT\r\n by reference ANY\r\n by reference STRING-LENGTH-CONSTANT\r\n returning RTNCODE\r\nend-call"],
        ["CBL_WRITE_SCR_CHARS", "call \"CBL_WRITE_SCR_CHARS\" using\r\n by reference SCREEN-POSITION-CONSTANT\r\n by reference ANY\r\n by reference STRING-LENGTH\r\n returning RTNCODE\r\nend-call"],
        ["CBL_WRITE_SCR_CHARS_ATTR", "call \"CBL_WRITE_SCR_CHARS_ATTR\" using\r\n by reference SCREEN-POSITION-CONSTANT\r\n by reference ANY\r\n by reference STRING-LENGTH\r\n by reference SCR-ATTRIBUTE\r\n returning RTNCODE\r\nend-call"],
        ["CBL_WRITE_SCR_CHATTRS", "call \"CBL_WRITE_SCR_CHATTRS\" using\r\n by reference SCREEN-POSITION-CONSTANT\r\n by reference cblt-alphanum-const\r\n by reference cblt-alphanum-const\r\n by reference STRING-LENGTH-CONSTANT\r\n returning RTNCODE\r\nend-call"],
        ["CBL_WRITE_SCR_N_ATTR", "call \"CBL_WRITE_SCR_N_ATTR\" using\r\n by reference SCREEN-POSITION-CONSTANT\r\n by reference SCR-ATTRIBUTE\r\n by reference STRING-LENGTH-CONSTANT\r\n returning RTNCODE\r\nend-call"],
        ["CBL_WRITE_SCR_N_CHAR", "call \"CBL_WRITE_SCR_N_CHAR\" using\r\n by reference SCREEN-POSITION-CONSTANT\r\n by reference ACHARACTER\r\n by reference STRING-LENGTH-CONSTANT\r\n returning RTNCODE\r\nend-call"],
        ["CBL_WRITE_SCR_N_CHATTR", "call \"CBL_WRITE_SCR_N_CHATTR\" using\r\n by reference SCREEN-POSITION-CONSTANT\r\n by reference ACHARACTER\r\n by reference SCR-ATTRIBUTE\r\n by reference STRING-LENGTH-CONSTANT\r\n returning RTNCODE\r\nend-call"],
        ["CBL_WRITE_SCR_TTY", "call \"CBL_WRITE_SCR_TTY\" using\r\n by reference cblt-alphanum-const\r\n by reference STRING-LENGTH-CONSTANT\r\n returning RTNCODE\r\nend-call"],
        ["CBL_GET_MOUSE_MASK", "call \"CBL_GET_MOUSE_MASK\" using\r\n by reference MOUSE-HANDLE\r\n by reference cblt-x2-compx\r\n returning STATUS-CODE\r\nend-call"],
        ["CBL_GET_MOUSE_POSITION", "call \"CBL_GET_MOUSE_POSITION\" using\r\n by reference MOUSE-HANDLE\r\n by reference MOUSE-POSITION\r\n returning STATUS-CODE\r\nend-call"],
        ["CBL_GET_MOUSE_STATUS", "call \"CBL_GET_MOUSE_STATUS\" using\r\n by reference MOUSE-HANDLE\r\n by reference MOUSE-QUEUE-SIZE\r\n returning STATUS-CODE\r\nend-call"],
        ["CBL_HIDE_MOUSE", "call \"CBL_HIDE_MOUSE\" using\r\n by reference MOUSE-HANDLE\r\n returning STATUS-CODE\r\nend-call"],
        ["CBL_INIT_MOUSE", "call \"CBL_INIT_MOUSE\" using\r\n by reference cblt-x4-compx\r\n by reference MOUSE-BUTTONS\r\n returning STATUS-CODE\r\nend-call"],
        ["CBL_READ_MOUSE_EVENT", "call \"CBL_READ_MOUSE_EVENT\" using\r\n by reference MOUSE-HANDLE\r\n by reference MOUSE-EVENT\r\n by reference READ-TYPE\r\n returning STATUS-CODE\r\nend-call"],
        ["CBL_SET_MOUSE_MASK", "call \"CBL_SET_MOUSE_MASK\" using\r\n by reference MOUSE-HANDLE\r\n by reference cblt-x2-compx-const\r\n returning STATUS-CODE\r\nend-call"],
        ["CBL_SET_MOUSE_POSITION", "call \"CBL_SET_MOUSE_POSITION\" using\r\n by reference MOUSE-HANDLE\r\n by reference MOUSE-POSITION-CONSTANT\r\n returning STATUS-CODE\r\nend-call"],
        ["CBL_SHOW_MOUSE", "call \"CBL_SHOW_MOUSE\" using\r\n by reference MOUSE-HANDLE\r\n returning STATUS-CODE\r\nend-call"],
        ["CBL_TERM_MOUSE", "call \"CBL_TERM_MOUSE\" using\r\n by reference cblt-x4-compx\r\n returning STATUS-CODE\r\nend-call"],
        ["PC_GET_MOUSE_SHAPE", "call \"PC_GET_MOUSE_SHAPE\" using\r\n by reference MOUSE-HANDLE\r\n by reference ANY\r\n by reference MOUSE-PTR-SHAPE-CONSTANT\r\n returning STATUS-CODE\r\nend-call"],
        ["PC_SET_MOUSE_HIDE_AREA", "call \"PC_SET_MOUSE_HIDE_AREA\" using\r\n by reference MOUSE-HANDLE\r\n by reference COLLISION-AREA\r\n returning STATUS-CODE\r\nend-call"],
        ["PC_SET_MOUSE_SHAPE", "call \"PC_SET_MOUSE_SHAPE\" using\r\n by reference MOUSE-HANDLE\r\n by reference ANY\r\n by reference MOUSE-PTR-SHAPE\r\n returning STATUS-CODE\r\nend-call"],
        ["PC_FIND_DRIVES", "call \"PC_FIND_DRIVES\" using\r\n by reference DRIVE-INFO\r\n returning PC-STATUS-CODE\r\nend-call"],
        ["PC_READ_DRIVE", "call \"PC_READ_DRIVE\" using\r\n by reference cblt-x1-compx\r\n returning PC-STATUS-CODE\r\nend-call"],
        ["PC_SET_DRIVE", "call \"PC_SET_DRIVE\" using\r\n by reference cblt-x1-compx-const\r\n returning PC-STATUS-CODE\r\nend-call"],
        ["PC_WIN_ABOUT", "call \"PC_WIN_ABOUT\" using\r\n by reference ANY\r\n by value ABOUT-LEN\r\n returning PC-STATUS-CODE\r\nend-call"],
        ["PC_WIN_CHAR_TO_OEM", "call \"PC_WIN_CHAR_TO_OEM\" using\r\n by reference cblt-alphanum-const\r\n by reference ANY\r\n by value SRC-LEN\r\n by value TGT-LEN\r\n returning PC-STATUS-CODE\r\nend-call"],
        ["PC_WIN_HANDLE", "call \"PC_WIN_HANDLE\" using\r\n by reference WIN-HANDLE\r\n returning PC-STATUS-CODE\r\nend-call"],
        ["PC_WIN_INIT", "call \"PC_WIN_INIT\" using\r\n by reference HINST\r\n by reference HPREVINST\r\n by reference LPSZCMDLINE\r\n by reference NCMDSHOW\r\n returning PC-STATUS-CODE\r\nend-call"],
        ["PC_WIN_OEM_TO_CHAR", "call \"PC_WIN_OEM_TO_CHAR\" using\r\n by reference cblt-alphanum-const\r\n by reference ANY\r\n by value SRC-LEN\r\n by value TGT-LEN\r\n returning PC-STATUS-CODE\r\nend-call"],
        ["PC_WIN_YIELD", "call \"PC_WIN_YIELD\" using\r\n returning PC-STATUS-CODE\r\nend-call"],
        ["CBL_CANCEL", "call \"CBL_CANCEL\" using\r\n by value CANCEL-FLAGS\r\n by reference cblt-alphanum-const\r\n returning CANCEL-RTNCODE\r\nend-call"],
        ["CBL_CANCEL_PROC", "call \"CBL_CANCEL_PROC\" using\r\n by value CANCEL-PROC-FUNCTION\r\n by reference CANCEL-PROC-PARAMBLOCK\r\n by value CANCEL-PROC-DATALENGTH\r\n returning CANCEL-PROC-RTNCODE\r\nend-call"],
        ["CBL_DEBUGBREAK", "call \"CBL_DEBUGBREAK\" using\r\n returning DBG-RTNCODE\r\nend-call"],
        ["CBL_DEBUG_START", "call \"CBL_DEBUG_START\" using\r\n by value DBG-FLAGS\r\n by value DBG-TIMEOUT\r\n by reference cblt-alphanum-const\r\n returning DBG-RTNCODE\r\nend-call"],
        ["CBL_DEBUG_STOP", "call \"CBL_DEBUG_STOP\" using\r\n by value DBG-FLAGS\r\n returning DBG-RTNCODE\r\nend-call"],
        ["CBL_FFND_REPORT", "call \"CBL_FFND_REPORT\" using\r\n by value FFR-RTSERR\r\n by value FFR-TERMINATE\r\n returning FFR-RTNCODE\r\nend-call"],
        ["CBL_GET_PROGRAM_INFO", "call \"CBL_GET_PROGRAM_INFO\" using\r\n by value GPI-FUNCTION\r\n by reference GPI-BLOCK\r\n by reference ANY\r\n by reference GPI-NAME-LEN\r\n returning GPI-RTNCODE\r\nend-call"],
        ["CBL_MONITOR_BROWSE", "call \"CBL_MONITOR_BROWSE\" using\r\n by value MON-HANDLE\r\n returning MON-RTNCODE\r\nend-call"],
        ["CBL_MONITOR_BROWSE_TO_READ", "call \"CBL_MONITOR_BROWSE_TO_READ\" using\r\n by value MON-HANDLE\r\n returning MON-RTNCODE\r\nend-call"],
        ["CBL_MONITOR_BROWSE_TO_WRITE", "call \"CBL_MONITOR_BROWSE_TO_WRITE\" using\r\n by value MON-HANDLE\r\n returning MON-RTNCODE\r\nend-call"],
        ["CBL_MONITOR_CLOSE", "call \"CBL_MONITOR_CLOSE\" using\r\n by value MON-HANDLE\r\n returning MON-RTNCODE\r\nend-call"],
        ["CBL_MONITOR_OPEN_INTRA", "call \"CBL_MONITOR_OPEN_INTRA\" using\r\n by reference MON-HANDLE\r\n by value MON-FLAGS\r\n returning MON-RTNCODE\r\nend-call"],
        ["CBL_MONITOR_READ", "call \"CBL_MONITOR_READ\" using\r\n by value MON-HANDLE\r\n returning MON-RTNCODE\r\nend-call"],
        ["CBL_MONITOR_RELEASE", "call \"CBL_MONITOR_RELEASE\" using\r\n by value MON-HANDLE\r\n returning MON-RTNCODE\r\nend-call"],
        ["CBL_MONITOR_UNBROWSE", "call \"CBL_MONITOR_UNBROWSE\" using\r\n by value MON-HANDLE\r\n returning MON-RTNCODE\r\nend-call"],
        ["CBL_MONITOR_UNREAD", "call \"CBL_MONITOR_UNREAD\" using\r\n by value MON-HANDLE\r\n returning MON-RTNCODE\r\nend-call"],
        ["CBL_MONITOR_UNWRITE", "call \"CBL_MONITOR_UNWRITE\" using\r\n by value MON-HANDLE\r\n returning MON-RTNCODE\r\nend-call"],
        ["CBL_MONITOR_WRITE", "call \"CBL_MONITOR_WRITE\" using\r\n by value MON-HANDLE\r\n returning MON-RTNCODE\r\nend-call"],
        ["CBL_MONITOR_WRITE_TO_BROWSE", "call \"CBL_MONITOR_WRITE_TO_BROWSE\" using\r\n by value MON-HANDLE\r\n returning MON-RTNCODE\r\nend-call"],
        ["CBL_MUTEX_ACQUIRE", "call \"CBL_MUTEX_ACQUIRE\" using\r\n by value MUT-HANDLE\r\n by value MUT-FLAGS\r\n returning MUT-RTNCODE\r\nend-call"],
        ["CBL_MUTEX_CLOSE", "call \"CBL_MUTEX_CLOSE\" using\r\n by value MUT-HANDLE\r\n returning MUT-RTNCODE\r\nend-call"],
        ["CBL_MUTEX_OPEN_INTRA", "call \"CBL_MUTEX_OPEN_INTRA\" using\r\n by reference MUT-HANDLE\r\n by value MUT-FLAGS\r\n returning MUT-RTNCODE\r\nend-call"],
        ["CBL_MUTEX_RELEASE", "call \"CBL_MUTEX_RELEASE\" using\r\n by value MUT-HANDLE\r\n returning MUT-RTNCODE\r\nend-call"],
        ["CBL_EVENT_CLEAR", "call \"CBL_EVENT_CLEAR\" using\r\n by value EVT-HANDLE\r\n returning EVT-RTNCODE\r\nend-call"],
        ["CBL_EVENT_CLOSE", "call \"CBL_EVENT_CLOSE\" using\r\n by value EVT-HANDLE\r\n returning EVT-RTNCODE\r\nend-call"],
        ["CBL_EVENT_OPEN_INTRA", "call \"CBL_EVENT_OPEN_INTRA\" using\r\n by reference EVT-HANDLE\r\n by value EVT-FLAGS\r\n returning EVT-RTNCODE\r\nend-call"],
        ["CBL_EVENT_POST", "call \"CBL_EVENT_POST\" using\r\n by value EVT-HANDLE\r\n returning EVT-RTNCODE\r\nend-call"],
        ["CBL_EVENT_WAIT", "call \"CBL_EVENT_WAIT\" using\r\n by value EVT-HANDLE\r\n by value EVT-FLAGS\r\n returning EVT-RTNCODE\r\nend-call"],
        ["CBL_SEMAPHORE_CLEAR", "call \"CBL_SEMAPHORE_CLEAR\" using\r\n by value SEM-HANDLE\r\n returning SEM-RTNCODE\r\nend-call"],
        ["CBL_SEMAPHORE_CLOSE", "call \"CBL_SEMAPHORE_CLOSE\" using\r\n by value SEM-HANDLE\r\n returning SEM-RTNCODE\r\nend-call"],
        ["CBL_SEMAPHORE_OPEN_INTRA", "call \"CBL_SEMAPHORE_OPEN_INTRA\" using\r\n by reference SEM-HANDLE\r\n by value SEM-START\r\n by value SEM-FLAGS\r\n returning SEM-RTNCODE\r\nend-call"],
        ["CBL_SEMAPHORE_POST", "call \"CBL_SEMAPHORE_POST\" using\r\n by value SEM-HANDLE\r\n returning SEM-RTNCODE\r\nend-call"],
        ["CBL_SEMAPHORE_WAIT", "call \"CBL_SEMAPHORE_WAIT\" using\r\n by value SEM-HANDLE\r\n by value SEM-FLAGS\r\n returning SEM-RTNCODE\r\nend-call"],
        ["CBL_TSTORE_CLOSE", "call \"CBL_TSTORE_CLOSE\" using\r\n by value TSTORE-HANDLE\r\n returning TSTORE-RTNCODE\r\nend-call"],
        ["CBL_TSTORE_CREATE", "call \"CBL_TSTORE_CREATE\" using\r\n by reference TSTORE-HANDLE\r\n by value TSTORE-SIZE\r\n by value TSTORE-FLAGS\r\n returning TSTORE-RTNCODE\r\nend-call"],
        ["CBL_TSTORE_GET", "call \"CBL_TSTORE_GET\" using\r\n by value TSTORE-HANDLE\r\n by reference TSTORE-PTR\r\n returning TSTORE-RTNCODE\r\nend-call"],
        ["CBL_THREAD_CREATE", "call \"CBL_THREAD_CREATE\" using\r\n by reference ANY\r\n by reference ANY\r\n by value THREAD-PARAM-SIZE\r\n by value THREAD-FLAGS\r\n by value THREAD-PRIORITY\r\n by value THREAD-STACK-SIZE\r\n by reference THREAD-HANDLE\r\n returning THREAD-RTNCODE\r\nend-call"],
        ["CBL_THREAD_CREATE_P", "call \"CBL_THREAD_CREATE_P\" using\r\n by value THREAD-ENTRY-PTR\r\n by reference ANY\r\n by value THREAD-PARAM-SIZE\r\n by value THREAD-FLAGS\r\n by value THREAD-PRIORITY\r\n by value THREAD-STACK-SIZE\r\n by reference THREAD-HANDLE\r\n returning THREAD-RTNCODE\r\nend-call"],
        ["CBL_THREAD_DETACH", "call \"CBL_THREAD_DETACH\" using\r\n by value THREAD-HANDLE\r\n returning THREAD-RTNCODE\r\nend-call"],
        ["CBL_THREAD_EXIT", "call \"CBL_THREAD_EXIT\" using\r\n by value THREAD-RTNVALUE\r\n returning THREAD-RTNCODE\r\nend-call"],
        ["CBL_THREAD_IDDATA_ALLOC", "call \"CBL_THREAD_IDDATA_ALLOC\" using\r\n by value THREAD-IDDATA\r\n by value THREAD-IDDATA-SIZE\r\n returning THREAD-RTNCODE\r\nend-call"],
        ["CBL_THREAD_IDDATA_GET", "call \"CBL_THREAD_IDDATA_GET\" using\r\n by reference THREAD-IDDATA\r\n by value THREAD-HANDLE\r\n returning THREAD-RTNCODE\r\nend-call"],
        ["CBL_THREAD_KILL", "call \"CBL_THREAD_KILL\" using\r\n by value THREAD-HANDLE\r\n returning THREAD-RTNCODE\r\nend-call"],
        ["CBL_THREAD_LIST_END", "call \"CBL_THREAD_LIST_END\" using\r\n returning THREAD-RTNCODE\r\nend-call"],
        ["CBL_THREAD_LIST_NEXT", "call \"CBL_THREAD_LIST_NEXT\" using\r\n by reference THREAD-HANDLE\r\n by reference THREAD-STATE\r\n by reference THREAD-IDDATA\r\n returning THREAD-RTNCODE\r\nend-call"],
        ["CBL_THREAD_LIST_START", "call \"CBL_THREAD_LIST_START\" using\r\n by reference THREAD-HANDLE\r\n by reference THREAD-STATE\r\n by reference THREAD-IDDATA\r\n returning THREAD-RTNCODE\r\nend-call"],
        ["CBL_THREAD_LOCK", "call \"CBL_THREAD_LOCK\" using\r\n returning THREAD-RTNCODE\r\nend-call"],
        ["CBL_THREAD_PROG_LOCK", "call \"CBL_THREAD_PROG_LOCK\" using\r\n returning THREAD-RTNCODE\r\nend-call"],
        ["CBL_THREAD_PROG_UNLOCK", "call \"CBL_THREAD_PROG_UNLOCK\" using\r\n returning THREAD-RTNCODE\r\nend-call"],
        ["CBL_THREAD_RESUME", "call \"CBL_THREAD_RESUME\" using\r\n by value THREAD-HANDLE\r\n returning THREAD-RTNCODE\r\nend-call"],
        ["CBL_THREAD_SELF", "call \"CBL_THREAD_SELF\" using\r\n by reference THREAD-HANDLE\r\n returning THREAD-RTNCODE\r\nend-call"],
        ["CBL_THREAD_SLEEP", "call \"CBL_THREAD_SLEEP\" using\r\n by value THREAD-SLEEP\r\n returning THREAD-RTNCODE\r\nend-call"],
        ["CBL_THREAD_SUSPEND", "call \"CBL_THREAD_SUSPEND\" using\r\n by value THREAD-HANDLE\r\n returning THREAD-RTNCODE\r\nend-call"],
        ["CBL_THREAD_UNLOCK", "call \"CBL_THREAD_UNLOCK\" using\r\n returning THREAD-RTNCODE\r\nend-call"],
        ["CBL_THREAD_WAIT", "call \"CBL_THREAD_WAIT\" using\r\n by value THREAD-HANDLE\r\n by reference THREAD-RTNVALUE\r\n returning THREAD-RTNCODE\r\nend-call"],
        ["CBL_THREAD_YIELD", "call \"CBL_THREAD_YIELD\" using\r\n returning THREAD-RTNCODE\r\nend-call"],
        ["CBL_SRV_SERVICE_FLAGS_GET", "call \"CBL_SRV_SERVICE_FLAGS_GET\" using\r\n by reference SERVICE-FLAGS\r\n returning RET\r\nend-call"],
        ["CBL_SRV_SERVICE_FLAGS_SET", "call \"CBL_SRV_SERVICE_FLAGS_SET\" using\r\n by value SERVICE-FLAGS-MASK\r\n by value SERVICE-FLAGS\r\n returning RET\r\nend-call"]
    ]);

    public snippets = new Map<string, string>([
        ["CBL_ALLOC_DYN_MEM", "call \"CBL_ALLOC_DYN_MEM\" using\r\n by reference ${1:MEM-POINTER}\r\n by value ${2:MEM-SIZE}\r\n by value ${3:MEM-FLAGS}\r\n returning ${4:MEM-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_ALLOC_MEM", "call \"CBL_ALLOC_MEM\" using\r\n by reference ${1:MEM-POINTER}\r\n by value ${2:MEM-SIZE}\r\n by value ${3:MEM-FLAGS}\r\n returning ${4:MEM-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_ALLOC_SHMEM", "call \"CBL_ALLOC_SHMEM\" using\r\n by reference ${1:MEM-POINTER}\r\n by value ${2:MEM-SIZE}\r\n by value ${3:MEM-FLAGS}\r\n returning ${4:MEM-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_ALLOC_THREAD_MEM", "call \"CBL_ALLOC_THREAD_MEM\" using\r\n by reference ${1:MEM-POINTER}\r\n by value ${2:MEM-SIZE}\r\n by value ${3:MEM-FLAGS}\r\n returning ${4:MEM-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_FREE_DYN_MEM", "call \"CBL_FREE_DYN_MEM\" using\r\n by value ${1:MEM-POINTER}\r\n returning ${2:MEM-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_FREE_MEM", "call \"CBL_FREE_MEM\" using\r\n by value ${1:MEM-POINTER}\r\n returning ${2:MEM-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_FREE_SHMEM", "call \"CBL_FREE_SHMEM\" using\r\n by value ${1:MEM-POINTER}\r\n returning ${2:MEM-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_FREE_THREAD_MEM", "call \"CBL_FREE_THREAD_MEM\" using\r\n by value ${1:MEM-POINTER}\r\n returning ${2:MEM-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_GET_SHMEM_PTR", "call \"CBL_GET_SHMEM_PTR\" using\r\n by reference ${1:MEM-NODE-VALUE}\r\n by reference ${2:ANY}\r\n returning ${3:MEM-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_PUT_SHMEM_PTR", "call \"CBL_PUT_SHMEM_PTR\" using\r\n by value ${1:MEM-NODE-VALUE}\r\n by reference ${2:ANY}\r\n returning ${3:MEM-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_MEM_STRATEGY", "call \"CBL_MEM_STRATEGY\" using\r\n by value ${1:MEM-FUNC}\r\n by reference ${2:MEM-STRATEGY-FLAGS}\r\n returning ${3:MEM-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_MEM_VALIDATE", "call \"CBL_MEM_VALIDATE\" using\r\n by value ${1:MEM-FLAGS}\r\n by reference ${2:MEM-VALIDATE-PARAM}\r\n returning ${3:MEM-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_AND", "call \"CBL_AND\" using\r\n by reference ${1:ANY}\r\n by reference ${2:ANY}\r\n by value ${3:LEN}\r\n returning ${4:RET}\r\nend-call\r\n${0}"],
        ["CBL_EQ", "call \"CBL_EQ\" using\r\n by reference ${1:ANY}\r\n by reference ${2:ANY}\r\n by value ${3:LEN}\r\n returning ${4:RET}\r\nend-call\r\n${0}"],
        ["CBL_GET_OS_INFO", "call \"CBL_GET_OS_INFO\" using\r\n by reference ${1:OS-INFO-BLOCK}\r\n returning ${2:RET}\r\nend-call\r\n${0}"],
        ["CBL_IMP", "call \"CBL_IMP\" using\r\n by reference ${1:ANY}\r\n by reference ${2:ANY}\r\n by value ${3:LEN}\r\n returning ${4:RET}\r\nend-call\r\n${0}"],
        ["CBL_NOT", "call \"CBL_NOT\" using\r\n by reference ${1:ANY}\r\n by value ${2:LEN}\r\n returning ${3:RET}\r\nend-call\r\n${0}"],
        ["CBL_OR", "call \"CBL_OR\" using\r\n by reference ${1:ANY}\r\n by reference ${2:ANY}\r\n by value ${3:LEN}\r\n returning ${4:RET}\r\nend-call\r\n${0}"],
        ["CBL_TOLOWER", "call \"CBL_TOLOWER\" using\r\n by reference ${1:ANY}\r\n by value ${2:LEN}\r\n returning ${3:RET}\r\nend-call\r\n${0}"],
        ["CBL_TOUPPER", "call \"CBL_TOUPPER\" using\r\n by reference ${1:ANY}\r\n by value ${2:LEN}\r\n returning ${3:RET}\r\nend-call\r\n${0}"],
        ["CBL_XOR", "call \"CBL_XOR\" using\r\n by reference ${1:ANY}\r\n by reference ${2:ANY}\r\n by value ${3:LEN}\r\n returning ${4:RET}\r\nend-call\r\n${0}"],
        ["CBL_CHANGE_DIR", "call \"CBL_CHANGE_DIR\" using\r\n by reference ${1:cblt-alphanum-const}\r\n returning ${2:CD-RET}\r\nend-call\r\n${0}"],
        ["CBL_CHECK_FILE_EXIST", "call \"CBL_CHECK_FILE_EXIST\" using\r\n by reference ${1:ANY}\r\n by reference ${2:FE-DETAILS}\r\n returning ${3:FE-RET}\r\nend-call\r\n${0}"],
        ["CBL_COPY_FILE", "call \"CBL_COPY_FILE\" using\r\n by reference ${1:cblt-alphanum-const}\r\n by reference ${2:cblt-alphanum-const}\r\n returning ${3:CF-RET}\r\nend-call\r\n${0}"],
        ["CBL_CREATE_DIR", "call \"CBL_CREATE_DIR\" using\r\n by reference ${1:cblt-alphanum-const}\r\n returning ${2:CD-RET}\r\nend-call\r\n${0}"],
        ["CBL_DELETE_DIR", "call \"CBL_DELETE_DIR\" using\r\n by reference ${1:cblt-alphanum-const}\r\n returning ${2:DD-RET}\r\nend-call\r\n${0}"],
        ["CBL_DELETE_FILE", "call \"CBL_DELETE_FILE\" using\r\n by reference ${1:cblt-alphanum-const}\r\n returning ${2:DF-RET}\r\nend-call\r\n${0}"],
        ["CBL_DIR_SCAN_END", "call \"CBL_DIR_SCAN_END\" using\r\n by reference ${1:DS-HANDLE}\r\n returning ${2:DS-RET}\r\nend-call\r\n${0}"],
        ["CBL_DIR_SCAN_READ", "call \"CBL_DIR_SCAN_READ\" using\r\n by reference ${1:DS-HANDLE}\r\n by reference ${2:ANY}\r\n returning ${3:DS-RET}\r\nend-call\r\n${0}"],
        ["CBL_DIR_SCAN_START", "call \"CBL_DIR_SCAN_START\" using\r\n by reference ${1:DS-HANDLE}\r\n by reference ${2:ANY}\r\n by value ${3:DS-ATTRS}\r\n by value ${4:DS-FLAGS}\r\n returning ${5:DS-RET}\r\nend-call\r\n${0}"],
        ["CBL_FILENAME_CONVERT", "call \"CBL_FILENAME_CONVERT\" using\r\n by reference ${1:FNC-FUNC}\r\n by reference ${2:cblt-alphanum-const}\r\n by reference ${3:ANY}\r\n by value ${4:FNC-IN-LENGTH}\r\n by value ${5:FNC-OUT-LENGTH}\r\n returning ${6:FNC-RET}\r\nend-call\r\n${0}"],
        ["CBL_FILENAME_MAX_LENGTH", "call \"CBL_FILENAME_MAX_LENGTH\" using\r\n returning ${1:FML-RET}\r\nend-call\r\n${0}"],
        ["CBL_GET_CURRENT_DIR", "call \"CBL_GET_CURRENT_DIR\" using\r\n by value ${1:GCD-FLAGS}\r\n by value ${2:GCD-NAME-LENGTH}\r\n by reference ${3:ANY}\r\n returning ${4:GCD-RET}\r\nend-call\r\n${0}"],
        ["CBL_GET_FILE_INFO", "call \"CBL_GET_FILE_INFO\" using\r\n by value ${1:FI-FLAGS}\r\n by reference ${2:cblt-alphanum-const}\r\n by reference ${3:FI-DETAILS}\r\n returning ${4:FI-RET}\r\nend-call\r\n${0}"],
        ["CBL_JOIN_FILENAME", "call \"CBL_JOIN_FILENAME\" using\r\n by reference ${1:SJ-PACKET}\r\n by reference ${2:ANY}\r\n by reference ${3:cblt-alphanum-const}\r\n by reference ${4:cblt-alphanum-const}\r\n by reference ${5:cblt-alphanum-const}\r\n returning ${6:SJ-RET}\r\nend-call\r\n${0}"],
        ["CBL_LOCATE_FILE", "call \"CBL_LOCATE_FILE\" using\r\n by reference ${1:cblt-alphanum-const}\r\n by reference ${2:LF-FUNC}\r\n by reference ${3:ANY}\r\n by reference ${4:LF-EXIST-FLAG}\r\n by reference ${5:LF-PATH-FLAG}\r\n returning ${6:LF-RET}\r\nend-call\r\n${0}"],
        ["CBL_RENAME_FILE", "call \"CBL_RENAME_FILE\" using\r\n by reference ${1:cblt-alphanum-const}\r\n by reference ${2:cblt-alphanum-const}\r\n returning ${3:RF-RET}\r\nend-call\r\n${0}"],
        ["CBL_SPLIT_FILENAME", "call \"CBL_SPLIT_FILENAME\" using\r\n by reference ${1:SJ-PACKET}\r\n by reference ${2:ANY}\r\n returning ${3:SJ-RET}\r\nend-call\r\n${0}"],
        ["CBL_NLS_CLOSE_MSG_FILE", "call \"CBL_NLS_CLOSE_MSG_FILE\" using\r\n by reference ${1:MSG-HANDLE}\r\n returning ${2:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_NLS_COMPARE", "call \"CBL_NLS_COMPARE\" using\r\n by reference ${1:cblt-alphanum-const}\r\n by reference ${2:cblt-alphanum-const}\r\n by value ${3:STRING-LENGTH}\r\n by value ${4:STRING-LENGTH}\r\n by reference ${5:COMPARE-RESULT}\r\n returning ${6:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_NLS_INFO", "call \"CBL_NLS_INFO\" using\r\n by reference ${1:INFO-FUNCTION-CODE}\r\n by reference ${2:INFO-CATEGORY}\r\n by reference ${3:ANY}\r\n returning ${4:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_NLS_OPEN_MSG_FILE", "call \"CBL_NLS_OPEN_MSG_FILE\" using\r\n by reference ${1:cblt-alphanum-const}\r\n by reference ${2:MSG-FILE-NAME-LENGTH}\r\n by reference ${3:MSG-HANDLE}\r\n returning ${4:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_NLS_READ_MSG", "call \"CBL_NLS_READ_MSG\" using\r\n by reference ${1:MSG-HANDLE-READONLY}\r\n by reference ${2:MSG-NUMBER-PAIR}\r\n by reference ${3:ANY}\r\n by reference ${4:ANY}\r\n returning ${5:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_ABORT_RUN_UNIT", "call \"CBL_ABORT_RUN_UNIT\" using\r\n by value ${1:RTNCODE}\r\n returning ${2:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_CULL_RUN_UNITS", "call \"CBL_CULL_RUN_UNITS\" using\r\n returning ${1:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_ERROR_PROC", "call \"CBL_ERROR_PROC\" using\r\n by reference ${1:INSTALL-FLAG}\r\n by reference ${2:INSTALL-ADDRS}\r\n returning ${3:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_EXEC_RUN_UNIT", "call \"CBL_EXEC_RUN_UNIT\" using\r\n by reference ${1:ANY}\r\n by value ${2:COMMAND-LINE-LEN}\r\n by reference ${3:RU-HANDLE}\r\n by value ${4:STACK-SIZE}\r\n by value ${5:FLAGS}\r\n returning ${6:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_EXIT_PROC", "call \"CBL_EXIT_PROC\" using\r\n by reference ${1:INSTALL-FLAG}\r\n by reference ${2:INSTALL-PARAMS}\r\n returning ${3:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_GET_EXIT_INFO", "call \"CBL_GET_EXIT_INFO\" using\r\n by reference ${1:GEI-PARAMS}\r\n returning ${2:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_SUBSYSTEM", "call \"CBL_SUBSYSTEM\" using\r\n by reference ${1:FUNCTION-CODE}\r\n by reference ${2:ANY}\r\n returning ${3:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_YIELD_RUN_UNIT", "call \"CBL_YIELD_RUN_UNIT\" using\r\n returning ${1:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_RUNTIME_ERROR", "call \"CBL_RUNTIME_ERROR\" using\r\n by value ${1:FLAGS}\r\n by reference ${2:cblt-alphanum-const}\r\n returning ${3:RTNCODE}\r\nend-call\r\n${0}"],
        ["SYSTEM", "call \"SYSTEM\" using\r\n by reference ${1:ANY}\r\n returning ${2:C-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_CLOSE_FILE", "call \"CBL_CLOSE_FILE\" using\r\n by reference ${1:FILE-HANDLE}\r\n returning ${2:RETURN-STAT}\r\nend-call\r\n${0}"],
        ["CBL_CREATE_FILE", "call \"CBL_CREATE_FILE\" using\r\n by reference ${1:cblt-alphanum-const}\r\n by reference ${2:ACCESS-MODE}\r\n by reference ${3:DENY-MODE}\r\n by reference ${4:DEVICE}\r\n by reference ${5:FILE-HANDLE}\r\n returning ${6:RETURN-STAT}\r\nend-call\r\n${0}"],
        ["CBL_FLUSH_FILE", "call \"CBL_FLUSH_FILE\" using\r\n by reference ${1:FILE-HANDLE}\r\n returning ${2:RETURN-STAT}\r\nend-call\r\n${0}"],
        ["CBL_FREE_RECORD_LOCK", "call \"CBL_FREE_RECORD_LOCK\" using\r\n by reference ${1:FILE-HANDLE}\r\n by reference ${2:RECORD-OFFSET}\r\n by reference ${3:RECORD-LENGTH}\r\n by reference ${4:RESERVED}\r\n returning ${5:RETURN-STAT}\r\nend-call\r\n${0}"],
        ["CBL_GET_RECORD_LOCK", "call \"CBL_GET_RECORD_LOCK\" using\r\n by reference ${1:FILE-HANDLE}\r\n by reference ${2:RECORD-OFFSET}\r\n by reference ${3:RECORD-LENGTH}\r\n by reference ${4:RESERVED}\r\n returning ${5:RETURN-STAT}\r\nend-call\r\n${0}"],
        ["CBL_OPEN_FILE", "call \"CBL_OPEN_FILE\" using\r\n by reference ${1:cblt-alphanum-const}\r\n by reference ${2:ACCESS-MODE}\r\n by reference ${3:DENY-MODE}\r\n by reference ${4:DEVICE}\r\n by reference ${5:FILE-HANDLE}\r\n returning ${6:RETURN-STAT}\r\nend-call\r\n${0}"],
        ["CBL_READ_FILE", "call \"CBL_READ_FILE\" using\r\n by reference ${1:FILE-HANDLE}\r\n by reference ${2:FILE-OFFSET}\r\n by reference ${3:BYTE-COUNT}\r\n by reference ${4:FILE-FLAGS}\r\n by reference ${5:ANY}\r\n returning ${6:RETURN-STAT}\r\nend-call\r\n${0}"],
        ["CBL_TEST_RECORD_LOCK", "call \"CBL_TEST_RECORD_LOCK\" using\r\n by reference ${1:FILE-HANDLE}\r\n by reference ${2:RECORD-OFFSET}\r\n by reference ${3:RECORD-LENGTH}\r\n by reference ${4:RESERVED}\r\n returning ${5:RETURN-STAT}\r\nend-call\r\n${0}"],
        ["CBL_WRITE_FILE", "call \"CBL_WRITE_FILE\" using\r\n by reference ${1:FILE-HANDLE}\r\n by reference ${2:FILE-OFFSET}\r\n by reference ${3:BYTE-COUNT}\r\n by reference ${4:FILE-FLAGS}\r\n by reference ${5:ANY}\r\n returning ${6:RETURN-STAT}\r\nend-call\r\n${0}"],
        ["CBL_CLOSE_VFILE", "call \"CBL_CLOSE_VFILE\" using\r\n by value ${1:HEAP-ID}\r\n returning ${2:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_OPEN_VFILE", "call \"CBL_OPEN_VFILE\" using\r\n by reference ${1:HEAP-ID}\r\n by reference ${2:STATUS-WORD}\r\n returning ${3:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_READ_VFILE", "call \"CBL_READ_VFILE\" using\r\n by value ${1:HEAP-ID}\r\n by value ${2:HEAP-REF}\r\n by value ${3:HEAP-LENGTH}\r\n by reference ${4:ANY}\r\n returning ${5:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_WRITE_VFILE", "call \"CBL_WRITE_VFILE\" using\r\n by value ${1:HEAP-ID}\r\n by value ${2:HEAP-REF}\r\n by value ${3:HEAP-LENGTH}\r\n by reference ${4:cblt-alphanum-const}\r\n returning ${5:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_CLEAR_SCR", "call \"CBL_CLEAR_SCR\" using\r\n by reference ${1:ACHARACTER}\r\n by reference ${2:SCR-ATTRIBUTE}\r\n returning ${3:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_GET_CSR_POS", "call \"CBL_GET_CSR_POS\" using\r\n by reference ${1:SCREEN-POSITION}\r\n returning ${2:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_GET_KBD_STATUS", "call \"CBL_GET_KBD_STATUS\" using\r\n by reference ${1:KEY-STATUS}\r\n returning ${2:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_GET_SCR_GRAPHICS", "call \"CBL_GET_SCR_GRAPHICS\" using\r\n by reference ${1:GRAPHICS-BUFFER}\r\n returning ${2:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_GET_SCR_LINE_DRAW", "call \"CBL_GET_SCR_LINE_DRAW\" using\r\n by reference ${1:LINE-DRAW-FUNCTION-CODE}\r\n by reference ${2:ANY}\r\n returning ${3:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_GET_SCR_SIZE", "call \"CBL_GET_SCR_SIZE\" using\r\n by reference ${1:SCREEN-DEPTH}\r\n by reference ${2:SCREEN-WIDTH}\r\n returning ${3:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_READ_KBD_CHAR", "call \"CBL_READ_KBD_CHAR\" using\r\n by reference ${1:CHAR}\r\n returning ${2:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_READ_SCR_ATTRS", "call \"CBL_READ_SCR_ATTRS\" using\r\n by reference ${1:SCREEN-POSITION-CONSTANT}\r\n by reference ${2:ANY}\r\n by reference ${3:STRING-LENGTH}\r\n returning ${4:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_READ_SCR_CHARS", "call \"CBL_READ_SCR_CHARS\" using\r\n by reference ${1:SCREEN-POSITION-CONSTANT}\r\n by reference ${2:ANY}\r\n by reference ${3:STRING-LENGTH}\r\n returning ${4:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_READ_SCR_CHATTRS", "call \"CBL_READ_SCR_CHATTRS\" using\r\n by reference ${1:SCREEN-POSITION-CONSTANT}\r\n by reference ${2:ANY}\r\n by reference ${3:ANY}\r\n by reference ${4:STRING-LENGTH}\r\n returning ${5:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_SCR_ALLOCATE_COLOR", "call \"CBL_SCR_ALLOCATE_COLOR\" using\r\n by reference ${1:TABLE-COUNT}\r\n by reference ${2:ANY}\r\n by reference ${3:ANY}\r\n by reference ${4:ANY}\r\n returning ${5:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_SCR_ALLOCATE_VC_COLOR", "call \"CBL_SCR_ALLOCATE_VC_COLOR\" using\r\n by reference ${1:TABLE-COUNT}\r\n by reference ${2:ANY}\r\n by reference ${3:ANY}\r\n returning ${4:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_SCR_CREATE_VC", "call \"CBL_SCR_CREATE_VC\" using\r\n returning ${1:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_SCR_DESTROY_VC", "call \"CBL_SCR_DESTROY_VC\" using\r\n returning ${1:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_SCR_GET_ATTRIBUTES", "call \"CBL_SCR_GET_ATTRIBUTES\" using\r\n by reference ${1:TABLE-COUNT}\r\n by reference ${2:ANY}\r\n by reference ${3:ANY}\r\n returning ${4:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_SCR_GET_ATTR_INFO", "call \"CBL_SCR_GET_ATTR_INFO\" using\r\n by reference ${1:SCR-ATTRIBUTE-INFORMATION}\r\n returning ${2:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_SCR_NAME_TO_RGB", "call \"CBL_SCR_NAME_TO_RGB\" using\r\n by reference ${1:cblt-alphanum-const}\r\n by reference ${2:ANY}\r\n returning ${3:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_SCR_QUERY_COLORMAP", "call \"CBL_SCR_QUERY_COLORMAP\" using\r\n by reference ${1:TABLE-COUNT}\r\n by reference ${2:cblt-x4-compx-const}\r\n by reference ${3:ANY}\r\n returning ${4:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_SCR_RESTORE", "call \"CBL_SCR_RESTORE\" using\r\n by value ${1:SCR-FLAGS}\r\n by value ${2:SCR-HANDLE}\r\n returning ${3:NEW-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_SCR_RESTORE_ATTRIBUTES", "call \"CBL_SCR_RESTORE_ATTRIBUTES\" using\r\n by reference ${1:SCR-HANDLE}\r\n returning ${2:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_SCR_SAVE", "call \"CBL_SCR_SAVE\" using\r\n by value ${1:SCR-FLAGS}\r\n by value ${2:TOP-LINE}\r\n by value ${3:BOTTOM-LINE}\r\n returning ${4:SCR-HANDLE}\r\nend-call\r\n${0}"],
        ["CBL_SCR_SAVE_ATTRIBUTES", "call \"CBL_SCR_SAVE_ATTRIBUTES\" using\r\n by reference ${1:SCR-HANDLE}\r\n returning ${2:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_SCR_SET_ATTRIBUTES", "call \"CBL_SCR_SET_ATTRIBUTES\" using\r\n by reference ${1:TABLE-COUNT}\r\n by reference ${2:cblt-x1-compx}\r\n by reference ${3:ANY}\r\n returning ${4:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_SCR_SET_PC_ATTRIBUTES", "call \"CBL_SCR_SET_PC_ATTRIBUTES\" using\r\n returning ${1:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_SET_CSR_POS", "call \"CBL_SET_CSR_POS\" using\r\n by reference ${1:SCREEN-POSITION-CONSTANT}\r\n returning ${2:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_SWAP_SCR_CHATTRS", "call \"CBL_SWAP_SCR_CHATTRS\" using\r\n by reference ${1:SCREEN-POSITION-CONSTANT}\r\n by reference ${2:ANY}\r\n by reference ${3:ANY}\r\n by reference ${4:STRING-LENGTH}\r\n returning ${5:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_WRITE_SCR_ATTRS", "call \"CBL_WRITE_SCR_ATTRS\" using\r\n by reference ${1:SCREEN-POSITION-CONSTANT}\r\n by reference ${2:ANY}\r\n by reference ${3:STRING-LENGTH-CONSTANT}\r\n returning ${4:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_WRITE_SCR_CHARS", "call \"CBL_WRITE_SCR_CHARS\" using\r\n by reference ${1:SCREEN-POSITION-CONSTANT}\r\n by reference ${2:ANY}\r\n by reference ${3:STRING-LENGTH}\r\n returning ${4:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_WRITE_SCR_CHARS_ATTR", "call \"CBL_WRITE_SCR_CHARS_ATTR\" using\r\n by reference ${1:SCREEN-POSITION-CONSTANT}\r\n by reference ${2:ANY}\r\n by reference ${3:STRING-LENGTH}\r\n by reference ${4:SCR-ATTRIBUTE}\r\n returning ${5:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_WRITE_SCR_CHATTRS", "call \"CBL_WRITE_SCR_CHATTRS\" using\r\n by reference ${1:SCREEN-POSITION-CONSTANT}\r\n by reference ${2:cblt-alphanum-const}\r\n by reference ${3:cblt-alphanum-const}\r\n by reference ${4:STRING-LENGTH-CONSTANT}\r\n returning ${5:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_WRITE_SCR_N_ATTR", "call \"CBL_WRITE_SCR_N_ATTR\" using\r\n by reference ${1:SCREEN-POSITION-CONSTANT}\r\n by reference ${2:SCR-ATTRIBUTE}\r\n by reference ${3:STRING-LENGTH-CONSTANT}\r\n returning ${4:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_WRITE_SCR_N_CHAR", "call \"CBL_WRITE_SCR_N_CHAR\" using\r\n by reference ${1:SCREEN-POSITION-CONSTANT}\r\n by reference ${2:ACHARACTER}\r\n by reference ${3:STRING-LENGTH-CONSTANT}\r\n returning ${4:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_WRITE_SCR_N_CHATTR", "call \"CBL_WRITE_SCR_N_CHATTR\" using\r\n by reference ${1:SCREEN-POSITION-CONSTANT}\r\n by reference ${2:ACHARACTER}\r\n by reference ${3:SCR-ATTRIBUTE}\r\n by reference ${4:STRING-LENGTH-CONSTANT}\r\n returning ${5:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_WRITE_SCR_TTY", "call \"CBL_WRITE_SCR_TTY\" using\r\n by reference ${1:cblt-alphanum-const}\r\n by reference ${2:STRING-LENGTH-CONSTANT}\r\n returning ${3:RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_GET_MOUSE_MASK", "call \"CBL_GET_MOUSE_MASK\" using\r\n by reference ${1:MOUSE-HANDLE}\r\n by reference ${2:cblt-x2-compx}\r\n returning ${3:STATUS-CODE}\r\nend-call\r\n${0}"],
        ["CBL_GET_MOUSE_POSITION", "call \"CBL_GET_MOUSE_POSITION\" using\r\n by reference ${1:MOUSE-HANDLE}\r\n by reference ${2:MOUSE-POSITION}\r\n returning ${3:STATUS-CODE}\r\nend-call\r\n${0}"],
        ["CBL_GET_MOUSE_STATUS", "call \"CBL_GET_MOUSE_STATUS\" using\r\n by reference ${1:MOUSE-HANDLE}\r\n by reference ${2:MOUSE-QUEUE-SIZE}\r\n returning ${3:STATUS-CODE}\r\nend-call\r\n${0}"],
        ["CBL_HIDE_MOUSE", "call \"CBL_HIDE_MOUSE\" using\r\n by reference ${1:MOUSE-HANDLE}\r\n returning ${2:STATUS-CODE}\r\nend-call\r\n${0}"],
        ["CBL_INIT_MOUSE", "call \"CBL_INIT_MOUSE\" using\r\n by reference ${1:cblt-x4-compx}\r\n by reference ${2:MOUSE-BUTTONS}\r\n returning ${3:STATUS-CODE}\r\nend-call\r\n${0}"],
        ["CBL_READ_MOUSE_EVENT", "call \"CBL_READ_MOUSE_EVENT\" using\r\n by reference ${1:MOUSE-HANDLE}\r\n by reference ${2:MOUSE-EVENT}\r\n by reference ${3:READ-TYPE}\r\n returning ${4:STATUS-CODE}\r\nend-call\r\n${0}"],
        ["CBL_SET_MOUSE_MASK", "call \"CBL_SET_MOUSE_MASK\" using\r\n by reference ${1:MOUSE-HANDLE}\r\n by reference ${2:cblt-x2-compx-const}\r\n returning ${3:STATUS-CODE}\r\nend-call\r\n${0}"],
        ["CBL_SET_MOUSE_POSITION", "call \"CBL_SET_MOUSE_POSITION\" using\r\n by reference ${1:MOUSE-HANDLE}\r\n by reference ${2:MOUSE-POSITION-CONSTANT}\r\n returning ${3:STATUS-CODE}\r\nend-call\r\n${0}"],
        ["CBL_SHOW_MOUSE", "call \"CBL_SHOW_MOUSE\" using\r\n by reference ${1:MOUSE-HANDLE}\r\n returning ${2:STATUS-CODE}\r\nend-call\r\n${0}"],
        ["CBL_TERM_MOUSE", "call \"CBL_TERM_MOUSE\" using\r\n by reference ${1:cblt-x4-compx}\r\n returning ${2:STATUS-CODE}\r\nend-call\r\n${0}"],
        ["PC_GET_MOUSE_SHAPE", "call \"PC_GET_MOUSE_SHAPE\" using\r\n by reference ${1:MOUSE-HANDLE}\r\n by reference ${2:ANY}\r\n by reference ${3:MOUSE-PTR-SHAPE-CONSTANT}\r\n returning ${4:STATUS-CODE}\r\nend-call\r\n${0}"],
        ["PC_SET_MOUSE_HIDE_AREA", "call \"PC_SET_MOUSE_HIDE_AREA\" using\r\n by reference ${1:MOUSE-HANDLE}\r\n by reference ${2:COLLISION-AREA}\r\n returning ${3:STATUS-CODE}\r\nend-call\r\n${0}"],
        ["PC_SET_MOUSE_SHAPE", "call \"PC_SET_MOUSE_SHAPE\" using\r\n by reference ${1:MOUSE-HANDLE}\r\n by reference ${2:ANY}\r\n by reference ${3:MOUSE-PTR-SHAPE}\r\n returning ${4:STATUS-CODE}\r\nend-call\r\n${0}"],
        ["PC_FIND_DRIVES", "call \"PC_FIND_DRIVES\" using\r\n by reference ${1:DRIVE-INFO}\r\n returning ${2:PC-STATUS-CODE}\r\nend-call\r\n${0}"],
        ["PC_READ_DRIVE", "call \"PC_READ_DRIVE\" using\r\n by reference ${1:cblt-x1-compx}\r\n returning ${2:PC-STATUS-CODE}\r\nend-call\r\n${0}"],
        ["PC_SET_DRIVE", "call \"PC_SET_DRIVE\" using\r\n by reference ${1:cblt-x1-compx-const}\r\n returning ${2:PC-STATUS-CODE}\r\nend-call\r\n${0}"],
        ["PC_WIN_ABOUT", "call \"PC_WIN_ABOUT\" using\r\n by reference ${1:ANY}\r\n by value ${2:ABOUT-LEN}\r\n returning ${3:PC-STATUS-CODE}\r\nend-call\r\n${0}"],
        ["PC_WIN_CHAR_TO_OEM", "call \"PC_WIN_CHAR_TO_OEM\" using\r\n by reference ${1:cblt-alphanum-const}\r\n by reference ${2:ANY}\r\n by value ${3:SRC-LEN}\r\n by value ${4:TGT-LEN}\r\n returning ${5:PC-STATUS-CODE}\r\nend-call\r\n${0}"],
        ["PC_WIN_HANDLE", "call \"PC_WIN_HANDLE\" using\r\n by reference ${1:WIN-HANDLE}\r\n returning ${2:PC-STATUS-CODE}\r\nend-call\r\n${0}"],
        ["PC_WIN_INIT", "call \"PC_WIN_INIT\" using\r\n by reference ${1:HINST}\r\n by reference ${2:HPREVINST}\r\n by reference ${3:LPSZCMDLINE}\r\n by reference ${4:NCMDSHOW}\r\n returning ${5:PC-STATUS-CODE}\r\nend-call\r\n${0}"],
        ["PC_WIN_OEM_TO_CHAR", "call \"PC_WIN_OEM_TO_CHAR\" using\r\n by reference ${1:cblt-alphanum-const}\r\n by reference ${2:ANY}\r\n by value ${3:SRC-LEN}\r\n by value ${4:TGT-LEN}\r\n returning ${5:PC-STATUS-CODE}\r\nend-call\r\n${0}"],
        ["PC_WIN_YIELD", "call \"PC_WIN_YIELD\" using\r\n returning ${1:PC-STATUS-CODE}\r\nend-call\r\n${0}"],
        ["CBL_CANCEL", "call \"CBL_CANCEL\" using\r\n by value ${1:CANCEL-FLAGS}\r\n by reference ${2:cblt-alphanum-const}\r\n returning ${3:CANCEL-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_CANCEL_PROC", "call \"CBL_CANCEL_PROC\" using\r\n by value ${1:CANCEL-PROC-FUNCTION}\r\n by reference ${2:CANCEL-PROC-PARAMBLOCK}\r\n by value ${3:CANCEL-PROC-DATALENGTH}\r\n returning ${4:CANCEL-PROC-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_DEBUGBREAK", "call \"CBL_DEBUGBREAK\" using\r\n returning ${1:DBG-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_DEBUG_START", "call \"CBL_DEBUG_START\" using\r\n by value ${1:DBG-FLAGS}\r\n by value ${2:DBG-TIMEOUT}\r\n by reference ${3:cblt-alphanum-const}\r\n returning ${4:DBG-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_DEBUG_STOP", "call \"CBL_DEBUG_STOP\" using\r\n by value ${1:DBG-FLAGS}\r\n returning ${2:DBG-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_FFND_REPORT", "call \"CBL_FFND_REPORT\" using\r\n by value ${1:FFR-RTSERR}\r\n by value ${2:FFR-TERMINATE}\r\n returning ${3:FFR-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_GET_PROGRAM_INFO", "call \"CBL_GET_PROGRAM_INFO\" using\r\n by value ${1:GPI-FUNCTION}\r\n by reference ${2:GPI-BLOCK}\r\n by reference ${3:ANY}\r\n by reference ${4:GPI-NAME-LEN}\r\n returning ${5:GPI-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_MONITOR_BROWSE", "call \"CBL_MONITOR_BROWSE\" using\r\n by value ${1:MON-HANDLE}\r\n returning ${2:MON-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_MONITOR_BROWSE_TO_READ", "call \"CBL_MONITOR_BROWSE_TO_READ\" using\r\n by value ${1:MON-HANDLE}\r\n returning ${2:MON-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_MONITOR_BROWSE_TO_WRITE", "call \"CBL_MONITOR_BROWSE_TO_WRITE\" using\r\n by value ${1:MON-HANDLE}\r\n returning ${2:MON-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_MONITOR_CLOSE", "call \"CBL_MONITOR_CLOSE\" using\r\n by value ${1:MON-HANDLE}\r\n returning ${2:MON-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_MONITOR_OPEN_INTRA", "call \"CBL_MONITOR_OPEN_INTRA\" using\r\n by reference ${1:MON-HANDLE}\r\n by value ${2:MON-FLAGS}\r\n returning ${3:MON-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_MONITOR_READ", "call \"CBL_MONITOR_READ\" using\r\n by value ${1:MON-HANDLE}\r\n returning ${2:MON-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_MONITOR_RELEASE", "call \"CBL_MONITOR_RELEASE\" using\r\n by value ${1:MON-HANDLE}\r\n returning ${2:MON-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_MONITOR_UNBROWSE", "call \"CBL_MONITOR_UNBROWSE\" using\r\n by value ${1:MON-HANDLE}\r\n returning ${2:MON-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_MONITOR_UNREAD", "call \"CBL_MONITOR_UNREAD\" using\r\n by value ${1:MON-HANDLE}\r\n returning ${2:MON-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_MONITOR_UNWRITE", "call \"CBL_MONITOR_UNWRITE\" using\r\n by value ${1:MON-HANDLE}\r\n returning ${2:MON-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_MONITOR_WRITE", "call \"CBL_MONITOR_WRITE\" using\r\n by value ${1:MON-HANDLE}\r\n returning ${2:MON-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_MONITOR_WRITE_TO_BROWSE", "call \"CBL_MONITOR_WRITE_TO_BROWSE\" using\r\n by value ${1:MON-HANDLE}\r\n returning ${2:MON-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_MUTEX_ACQUIRE", "call \"CBL_MUTEX_ACQUIRE\" using\r\n by value ${1:MUT-HANDLE}\r\n by value ${2:MUT-FLAGS}\r\n returning ${3:MUT-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_MUTEX_CLOSE", "call \"CBL_MUTEX_CLOSE\" using\r\n by value ${1:MUT-HANDLE}\r\n returning ${2:MUT-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_MUTEX_OPEN_INTRA", "call \"CBL_MUTEX_OPEN_INTRA\" using\r\n by reference ${1:MUT-HANDLE}\r\n by value ${2:MUT-FLAGS}\r\n returning ${3:MUT-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_MUTEX_RELEASE", "call \"CBL_MUTEX_RELEASE\" using\r\n by value ${1:MUT-HANDLE}\r\n returning ${2:MUT-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_EVENT_CLEAR", "call \"CBL_EVENT_CLEAR\" using\r\n by value ${1:EVT-HANDLE}\r\n returning ${2:EVT-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_EVENT_CLOSE", "call \"CBL_EVENT_CLOSE\" using\r\n by value ${1:EVT-HANDLE}\r\n returning ${2:EVT-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_EVENT_OPEN_INTRA", "call \"CBL_EVENT_OPEN_INTRA\" using\r\n by reference ${1:EVT-HANDLE}\r\n by value ${2:EVT-FLAGS}\r\n returning ${3:EVT-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_EVENT_POST", "call \"CBL_EVENT_POST\" using\r\n by value ${1:EVT-HANDLE}\r\n returning ${2:EVT-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_EVENT_WAIT", "call \"CBL_EVENT_WAIT\" using\r\n by value ${1:EVT-HANDLE}\r\n by value ${2:EVT-FLAGS}\r\n returning ${3:EVT-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_SEMAPHORE_CLEAR", "call \"CBL_SEMAPHORE_CLEAR\" using\r\n by value ${1:SEM-HANDLE}\r\n returning ${2:SEM-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_SEMAPHORE_CLOSE", "call \"CBL_SEMAPHORE_CLOSE\" using\r\n by value ${1:SEM-HANDLE}\r\n returning ${2:SEM-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_SEMAPHORE_OPEN_INTRA", "call \"CBL_SEMAPHORE_OPEN_INTRA\" using\r\n by reference ${1:SEM-HANDLE}\r\n by value ${2:SEM-START}\r\n by value ${3:SEM-FLAGS}\r\n returning ${4:SEM-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_SEMAPHORE_POST", "call \"CBL_SEMAPHORE_POST\" using\r\n by value ${1:SEM-HANDLE}\r\n returning ${2:SEM-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_SEMAPHORE_WAIT", "call \"CBL_SEMAPHORE_WAIT\" using\r\n by value ${1:SEM-HANDLE}\r\n by value ${2:SEM-FLAGS}\r\n returning ${3:SEM-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_TSTORE_CLOSE", "call \"CBL_TSTORE_CLOSE\" using\r\n by value ${1:TSTORE-HANDLE}\r\n returning ${2:TSTORE-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_TSTORE_CREATE", "call \"CBL_TSTORE_CREATE\" using\r\n by reference ${1:TSTORE-HANDLE}\r\n by value ${2:TSTORE-SIZE}\r\n by value ${3:TSTORE-FLAGS}\r\n returning ${4:TSTORE-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_TSTORE_GET", "call \"CBL_TSTORE_GET\" using\r\n by value ${1:TSTORE-HANDLE}\r\n by reference ${2:TSTORE-PTR}\r\n returning ${3:TSTORE-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_THREAD_CREATE", "call \"CBL_THREAD_CREATE\" using\r\n by reference ${1:ANY}\r\n by reference ${2:ANY}\r\n by value ${3:THREAD-PARAM-SIZE}\r\n by value ${4:THREAD-FLAGS}\r\n by value ${5:THREAD-PRIORITY}\r\n by value ${6:THREAD-STACK-SIZE}\r\n by reference ${7:THREAD-HANDLE}\r\n returning ${8:THREAD-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_THREAD_CREATE_P", "call \"CBL_THREAD_CREATE_P\" using\r\n by value ${1:THREAD-ENTRY-PTR}\r\n by reference ${2:ANY}\r\n by value ${3:THREAD-PARAM-SIZE}\r\n by value ${4:THREAD-FLAGS}\r\n by value ${5:THREAD-PRIORITY}\r\n by value ${6:THREAD-STACK-SIZE}\r\n by reference ${7:THREAD-HANDLE}\r\n returning ${8:THREAD-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_THREAD_DETACH", "call \"CBL_THREAD_DETACH\" using\r\n by value ${1:THREAD-HANDLE}\r\n returning ${2:THREAD-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_THREAD_EXIT", "call \"CBL_THREAD_EXIT\" using\r\n by value ${1:THREAD-RTNVALUE}\r\n returning ${2:THREAD-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_THREAD_IDDATA_ALLOC", "call \"CBL_THREAD_IDDATA_ALLOC\" using\r\n by value ${1:THREAD-IDDATA}\r\n by value ${2:THREAD-IDDATA-SIZE}\r\n returning ${3:THREAD-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_THREAD_IDDATA_GET", "call \"CBL_THREAD_IDDATA_GET\" using\r\n by reference ${1:THREAD-IDDATA}\r\n by value ${2:THREAD-HANDLE}\r\n returning ${3:THREAD-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_THREAD_KILL", "call \"CBL_THREAD_KILL\" using\r\n by value ${1:THREAD-HANDLE}\r\n returning ${2:THREAD-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_THREAD_LIST_END", "call \"CBL_THREAD_LIST_END\" using\r\n returning ${1:THREAD-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_THREAD_LIST_NEXT", "call \"CBL_THREAD_LIST_NEXT\" using\r\n by reference ${1:THREAD-HANDLE}\r\n by reference ${2:THREAD-STATE}\r\n by reference ${3:THREAD-IDDATA}\r\n returning ${4:THREAD-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_THREAD_LIST_START", "call \"CBL_THREAD_LIST_START\" using\r\n by reference ${1:THREAD-HANDLE}\r\n by reference ${2:THREAD-STATE}\r\n by reference ${3:THREAD-IDDATA}\r\n returning ${4:THREAD-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_THREAD_LOCK", "call \"CBL_THREAD_LOCK\" using\r\n returning ${1:THREAD-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_THREAD_PROG_LOCK", "call \"CBL_THREAD_PROG_LOCK\" using\r\n returning ${1:THREAD-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_THREAD_PROG_UNLOCK", "call \"CBL_THREAD_PROG_UNLOCK\" using\r\n returning ${1:THREAD-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_THREAD_RESUME", "call \"CBL_THREAD_RESUME\" using\r\n by value ${1:THREAD-HANDLE}\r\n returning ${2:THREAD-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_THREAD_SELF", "call \"CBL_THREAD_SELF\" using\r\n by reference ${1:THREAD-HANDLE}\r\n returning ${2:THREAD-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_THREAD_SLEEP", "call \"CBL_THREAD_SLEEP\" using\r\n by value ${1:THREAD-SLEEP}\r\n returning ${2:THREAD-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_THREAD_SUSPEND", "call \"CBL_THREAD_SUSPEND\" using\r\n by value ${1:THREAD-HANDLE}\r\n returning ${2:THREAD-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_THREAD_UNLOCK", "call \"CBL_THREAD_UNLOCK\" using\r\n returning ${1:THREAD-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_THREAD_WAIT", "call \"CBL_THREAD_WAIT\" using\r\n by value ${1:THREAD-HANDLE}\r\n by reference ${2:THREAD-RTNVALUE}\r\n returning ${3:THREAD-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_THREAD_YIELD", "call \"CBL_THREAD_YIELD\" using\r\n returning ${1:THREAD-RTNCODE}\r\nend-call\r\n${0}"],
        ["CBL_SRV_SERVICE_FLAGS_GET", "call \"CBL_SRV_SERVICE_FLAGS_GET\" using\r\n by reference ${1:SERVICE-FLAGS}\r\n returning ${2:RET}\r\nend-call\r\n${0}"],
        ["CBL_SRV_SERVICE_FLAGS_SET", "call \"CBL_SRV_SERVICE_FLAGS_SET\" using\r\n by value ${1:SERVICE-FLAGS-MASK}\r\n by value ${2:SERVICE-FLAGS}\r\n returning ${3:RET}\r\nend-call\r\n${0}"]
    ]);
}




